import type { Break } from './types.ts'

/**
 * Список сломов куска S11 — содержание экрана: стало лучше или хуже.
 *
 * Список растёт по шагам нового порядка задач (план, раздел «Новый порядок задач»): каждый шаг
 * дописывает свои строки и заканчивается прогоном этих строк на полностью зелёном наборе.
 *
 * **Набор проверок у каждого слома — весь `npm test`, а не файл.** Узкий набор у сломов разметки
 * трёх прежних кусков — названная отложенная задача S10: слом, прогнанный по одному файлу, не
 * видит красного в соседних. Здесь лишнее красное обязано быть видно прибору.
 *
 * **Шаг 1 — водопад.** Ступени не считают денег сами: они раскладывают строку итогов месяца,
 * `MONTH_TOTALS` целиком. Сломы ниже бьют по раскладке — порядку, долям, краям, итогам от нуля —
 * и по тому, что отчёт вообще читает водопад.
 */

const ВОДОПАД_ПОРЯДОК = 'в водопаде ровно девять ступеней, в названном порядке'
const ВОДОПАД_КОЛОНКИ =
  'каждая ступень печатает свою колонку итогов, прибыль — та же колонка, что прибыль итога'
const ВОДОПАД_ПРОЦЕНТЫ = 'доли ступеней отданы процентами, а не долями единицы'
const ВОДОПАД_ОТ_ОБОРОТА = 'доли ступеней считаются от оборота, а не от чистой выручки'
const ВОДОПАД_СХОДИТСЯ = 'ступени водопада сходятся: вычитания висят от остатка и кончаются на итоге'
const ВОДОПАД_ИТОГИ_ОТ_НУЛЯ =
  'три итога водопада — от нуля; отрицательная прибыль идёт вниз, и шкала опускается под ноль'
const ВОДОПАД_ОБОРОТ_НОЛЬ = 'оборот ноль — доли, края и шкала пусты, а не нули'
const ВОДОПАД_В_ОТЧЁТЕ = 'отчёт несёт водопад из девяти ступеней, прочитанный тем же снимком'

const ДОЛЯ = 'round(s.amount / nullif(b.gross, 0) * 100, 1)::text'

const ВИД_ОДНО_ЗНАЧЕНИЕ = 'столбик ступени берёт ту же долю и тот же край, что напечатаны'
const ВИД_БАЗА = 'у каждой ступени названа база доли — оборот'
const ВИД_ПРИЗНАК = 'итог и вычитание различены признаком в разметке, а не только цветом'
const ВИД_ФОРМА = 'у итога водопада признак формы: полужирные подпись и сумма'
const ВИД_НОЛЬ = 'оборот ноль — у ступеней слова, столбиков нет'
const ВИД_ЯЧЕЙКИ = 'подписи ступеней водопада — отдельной ячейкой вне дорожки столбика'
const ПЕРЕПИСЬ = 'перепись экрана: весь видимый текст, по порядку и без единой потери'
const РАСХОЖДЕНИЕ =
  'напечатанное расхождение равно фактической разнице между суммой показанных ступеней и показанным итогом'
const РАСХОЖДЕНИЕ_СТРОКА = 'строка о расхождении — только когда оно есть, и с тем числом, что дал отчёт'
const ХВОСТ_ПРИБЫЛИ = '                  - t.fixed::numeric - t.profit::numeric, 0)'
const СЪЕДАЕТ_СРЕДИ = 'самое большое вычитание помечено среди вычитаний, итоги не помечаются'
const СЪЕДАЕТ_РАВЕНСТВО = 'при равенстве двух вычитаний до цента помечены оба'
const СЪЕДАЕТ_НОЛЬ = 'все вычитания ноль — не помечено ничего'
const СЪЕДАЕТ_ДОЛЯ = 'строка «съедает больше всего» называет помеченную ступень и берёт её же долю'
const СЪЕДАЕТ_ПОРОВНУ = 'при равенстве строка называет обе ступени поровну'
const СЪЕДАЕТ_БЕЗ_ДОЛИ = 'без доли строки «съедает больше всего» нет'
const СЪЕДАЕТ_ЦВЕТ = 'у строки «съедает больше всего» нет своего цвета — это подпись, а не тревога'
const ПРИЗНАК = "(s.kind = 'вычитание'\n        and s.amount > 0\n        and s.amount = max(s.amount) filter (where s.kind = 'вычитание') over ())"

export const BREAKS: Break[] = [
  {
    id: 'waterfall-chain-broken',
    claim: 'изменить одну ступень так, что остаток после вычитаний перестаёт сходиться с итогом',
    mustRedden: ВОДОПАД_СХОДИТСЯ,
    file: 'lib/metrics/sql.ts',
    find: '- t.fees::numeric),',
    replace: '),',
    tests: 'все',
  },
  {
    id: 'waterfall-fractions',
    claim: 'отдать доли ступеней долями единицы вместо процентов',
    mustRedden: ВОДОПАД_ПРОЦЕНТЫ,
    alsoRedden: [
      { name: ВОДОПАД_ОТ_ОБОРОТА, why: 'она сличает доли с процентами от оборота: 10,0 против 0,1' },
      { name: ВОДОПАД_СХОДИТСЯ, why: 'она сличает нижний край «постоянных» (проценты) с долей прибыли' },
      { name: ВОДОПАД_ИТОГИ_ОТ_НУЛЯ, why: 'она ждёт долю прибыли −10,0, а придёт −0,1' },
    ],
    file: 'lib/metrics/sql.ts',
    find: ДОЛЯ,
    replace: 'round(s.amount / nullif(b.gross, 0), 1)::text',
    tests: 'все',
  },
  {
    id: 'waterfall-share-of-net',
    claim: 'считать долю ступени от чистой выручки, а не от оборота',
    mustRedden: ВОДОПАД_ОТ_ОБОРОТА,
    alsoRedden: [
      { name: ВОДОПАД_СХОДИТСЯ, why: 'доля прибыли от чистой выручки перестаёт совпадать с краем, посчитанным от оборота' },
      { name: ВОДОПАД_ИТОГИ_ОТ_НУЛЯ, why: 'доля прибыли от чистой выручки — −11,8, а не −10,0' },
    ],
    file: 'lib/metrics/sql.ts',
    find: ДОЛЯ,
    replace: 'round(s.amount / nullif((select t.net::numeric from totals_row t), 0) * 100, 1)::text',
    tests: 'все',
  },
  {
    id: 'waterfall-step-dropped',
    claim: 'убрать ступень «чистая выручка» из набора',
    mustRedden: ВОДОПАД_ПОРЯДОК,
    alsoRedden: [
      { name: ВОДОПАД_КОЛОНКИ, why: 'она сличает все девять колонок, а ступеней становится восемь' },
      { name: ВОДОПАД_СХОДИТСЯ, why: 'она читает край и долю ступени «чистая выручка»' },
      { name: ВОДОПАД_ИТОГИ_ОТ_НУЛЯ, why: 'она читает край ступени «чистая выручка»' },
      { name: ВОДОПАД_В_ОТЧЁТЕ, why: 'она сличает порядок ступеней отчёта' },
      { name: РАСХОЖДЕНИЕ, why: 'она сличает расхождение из строки итогов с разницей сумм, которые показали ступени; ступень не из своей колонки ломает это равенство' },
    ],
    file: 'lib/metrics/sql.ts',
    find:
      "     (4, 'net',       'итог',      t.net::numeric,       0::numeric,\n" +
      '                                   t.net::numeric),\n',
    replace: '',
    tests: 'все',
  },
  {
    id: 'waterfall-second-profit',
    claim: 'завести прибыли ступени второе выражение из слагаемых вместо колонки прибыли итога',
    mustRedden: ВОДОПАД_КОЛОНКИ,
    alsoRedden: [
      { name: РАСХОЖДЕНИЕ, why: 'она сличает расхождение из строки итогов с разницей сумм, которые показали ступени; ступень не из своей колонки ломает это равенство' },
    ],
    file: 'lib/metrics/sql.ts',
    find: "(9, 'profit',    'итог',      t.profit::numeric,",
    replace:
      "(9, 'profit',    'итог',      t.net::numeric - t.cogs::numeric - t.ads::numeric - t.fees::numeric - t.fixed::numeric,",
    tests: 'все',
  },
  {
    id: 'waterfall-second-net',
    claim: 'посчитать промежуточный итог своим выражением вместо колонки чистой выручки итога',
    mustRedden: ВОДОПАД_КОЛОНКИ,
    alsoRedden: [
      { name: РАСХОЖДЕНИЕ, why: 'она сличает расхождение из строки итогов с разницей сумм, которые показали ступени; ступень не из своей колонки ломает это равенство' },
    ],
    file: 'lib/metrics/sql.ts',
    find: "(4, 'net',       'итог',      t.net::numeric,       0::numeric,",
    replace:
      "(4, 'net',       'итог',      t.gross::numeric - t.discounts::numeric - t.refunds::numeric,       0::numeric,",
    tests: 'все',
  },
  {
    id: 'waterfall-total-floats',
    claim: 'нарисовать промежуточный итог висящим от остатка, а не от нуля',
    mustRedden: ВОДОПАД_ИТОГИ_ОТ_НУЛЯ,
    alsoRedden: [{ name: ВОДОПАД_СХОДИТСЯ, why: 'она сличает края всех ступеней, край итога — ноль' }],
    file: 'lib/metrics/sql.ts',
    find: "(4, 'net',       'итог',      t.net::numeric,       0::numeric,",
    replace:
      "(4, 'net',       'итог',      t.net::numeric,       t.gross::numeric - t.discounts::numeric - t.refunds::numeric,",
    tests: 'все',
  },
  {
    id: 'waterfall-zero-share',
    claim: 'при нулевом обороте отдать долю ступени нулём, а не пустотой',
    mustRedden: ВОДОПАД_ОБОРОТ_НОЛЬ,
    file: 'lib/metrics/sql.ts',
    find: ДОЛЯ,
    replace: 'coalesce(round(s.amount / nullif(b.gross, 0) * 100, 1), 0)::text',
    tests: 'все',
  },
  {
    id: 'waterfall-not-in-report',
    claim: 'не прочитать водопад в отчёте',
    mustRedden: ВОДОПАД_В_ОТЧЁТЕ,
    file: 'lib/metrics/report.ts',
    find: '    const waterfallResult = await client.query(MONTH_WATERFALL, [dayParam])\n',
    replace: '    const waterfallResult = { rows: [] as Array<Record<string, unknown>> }\n',
    tests: 'все',
  },

  // Шаг 1, разметка и вид. Слома «блок рисуется и без своего поля» здесь нет, и это решение, а не
  // пропуск: такая разметка роняет отрисовку каждой принятой проверки, чья раскладка поля не несёт,
  // — два десятка проверок разом, и строка слома свелась бы к объявлению их всех «заодно».
  {
    id: 'waterfall-bar-other-value',
    claim: 'взять для длины столбика не ту долю, что напечатана текстом',
    mustRedden: ВИД_ОДНО_ЗНАЧЕНИЕ,
    file: 'app/page.tsx',
    find: "'--step-size': ступень.sharePct,",
    replace: "'--step-size': ступень.basePct,",
    tests: 'все',
  },
  {
    id: 'waterfall-base-unnamed',
    claim: 'печатать долю ступени без базы — без слова «оборота»',
    mustRedden: ВИД_БАЗА,
    alsoRedden: [
      { name: ВИД_ОДНО_ЗНАЧЕНИЕ, why: 'она ждёт текст доли вместе с базой: «37,5 % оборота»' },
      { name: ПЕРЕПИСЬ, why: 'в её списке у каждой ступени стоит «… % оборота»' },
    ],
    file: 'app/page.tsx',
    find: '`${percent(ступень.sharePct)} оборота`',
    replace: 'percent(ступень.sharePct)',
    tests: 'все',
  },
  {
    id: 'waterfall-kind-dropped',
    claim: 'снять со ступени признак итога или вычитания',
    mustRedden: ВИД_ПРИЗНАК,
    file: 'app/page.tsx',
    find: '<li key={ступень.key} data-kind={ступень.kind}>',
    replace: '<li key={ступень.key}>',
    tests: 'все',
  },
  {
    id: 'waterfall-total-weight-dropped',
    claim: 'снять у итога водопада полужирные подпись и сумму — оставить различие одним цветом',
    mustRedden: ВИД_ФОРМА,
    file: 'app/globals.css',
    find: '  font-weight: var(--fontWeightSemibold);\n}\n\n/*\n * Вычитание — светлая заливка',
    replace: '}\n\n/*\n * Вычитание — светлая заливка',
    tests: 'все',
  },
  {
    id: 'waterfall-zero-bar',
    claim: 'рисовать столбик ступени и тогда, когда доли нет',
    mustRedden: ВИД_НОЛЬ,
    file: 'app/page.tsx',
    find: '{ступень.sharePct !== null && ступень.basePct !== null && (',
    replace: '{(',
    tests: 'все',
  },
  {
    id: 'waterfall-label-in-track',
    claim: 'положить подпись ступени внутрь дорожки столбика',
    mustRedden: ВИД_ЯЧЕЙКИ,
    file: 'app/page.tsx',
    find:
      '                <span className="waterfall-label">\n' +
      '                  {ПОДПИСИ_СТУПЕНЕЙ[ступень.key] ?? ступень.key}\n' +
      '                </span>\n' +
      '                <span className="waterfall-track" aria-hidden="true">\n',
    replace:
      '                <span className="waterfall-track" aria-hidden="true">\n' +
      '                <span className="waterfall-label">\n' +
      '                  {ПОДПИСИ_СТУПЕНЕЙ[ступень.key] ?? ступень.key}\n' +
      '                </span>\n',
    tests: 'все',
  },

  // Шаг 1, расхождение цепочки с итогом — решение владельца по развилке Ж2. Утверждение без порога:
  // напечатанное число — ровно разница показанных сумм, и проверка считает её сама, в центах.
  {
    id: 'waterfall-gap-not-actual',
    claim: 'отдать расхождение с прибылью, не равное разнице показанных сумм — без одного слагаемого',
    mustRedden: РАСХОЖДЕНИЕ,
    file: 'lib/metrics/sql.ts',
    find: ХВОСТ_ПРИБЫЛИ,
    replace: '                  - t.profit::numeric, 0)',
    tests: 'все',
  },
  {
    id: 'waterfall-gap-zero-given',
    claim: 'отдать нулевое расхождение нулём, а не пустотой',
    mustRedden: РАСХОЖДЕНИЕ,
    file: 'lib/metrics/sql.ts',
    find: 'nullif(t.net::numeric - t.cogs::numeric - t.ads::numeric - t.fees::numeric',
    replace: '(t.net::numeric - t.cogs::numeric - t.ads::numeric - t.fees::numeric',
    andThen: { find: ХВОСТ_ПРИБЫЛИ, replace: '                  - t.fixed::numeric - t.profit::numeric)' },
    tests: 'все',
  },
  {
    id: 'waterfall-gap-line-without-gap',
    claim: 'печатать строку о расхождении и тогда, когда расхождения нет',
    mustRedden: РАСХОЖДЕНИЕ_СТРОКА,
    alsoRedden: [
      { name: 'экран содержит кнопку и оборачивает ею отчёт', why: 'она рисует настоящую страницу на местной базе; у посева расхождения нет, и строка с пустым числом роняет отрисовку' },
    ],
    file: 'app/page.tsx',
    find: "{typeof report.waterfall.profitGap === 'string' && (",
    replace: '{report.waterfall.profitGap !== undefined && (',
    tests: 'все',
  },

  // Шаг 1, строка «съедает больше всего» — решение владельца. Признак ставит запрос водопада; при
  // равенстве до цента помечены все равные, и строка называет их поровну.
  {
    id: 'largest-among-all',
    claim: 'искать самое большое среди всех ступеней, а не среди вычитаний',
    mustRedden: СЪЕДАЕТ_СРЕДИ,
    alsoRedden: [
      { name: СЪЕДАЕТ_РАВЕНСТВО, why: 'оборот больше любого вычитания и оказывается помеченным и там' },
      { name: СЪЕДАЕТ_НОЛЬ, why: 'оборот 500 помечается, хотя вычитания все ноль' },
    ],
    file: 'lib/metrics/sql.ts',
    find: ПРИЗНАК,
    replace: '(s.amount > 0\n        and s.amount = max(s.amount) over ())',
    tests: 'все',
  },
  {
    id: 'largest-tie-first-only',
    claim: 'при равенстве двух вычитаний до цента пометить только первое по порядку',
    mustRedden: СЪЕДАЕТ_РАВЕНСТВО,
    file: 'lib/metrics/sql.ts',
    find: "and s.amount = max(s.amount) filter (where s.kind = 'вычитание') over ())",
    replace:
      "and s.ord = first_value(s.ord) over (order by (s.kind = 'вычитание') desc, s.amount desc, s.ord))",
    tests: 'все',
  },
  {
    id: 'largest-zero-marked',
    claim: 'пометить самым большим нулевое вычитание, когда все вычитания ноль',
    mustRedden: СЪЕДАЕТ_НОЛЬ,
    file: 'lib/metrics/sql.ts',
    find: '        and s.amount > 0\n',
    replace: '',
    tests: 'все',
  },
  {
    id: 'largest-share-other-step',
    claim: 'назвать в строке одну ступень, а долю взять у другой',
    mustRedden: СЪЕДАЕТ_ДОЛЯ,
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'в её списке строка несёт долю помеченной ступени, 18,8 %' }],
    file: 'app/page.tsx',
    find: '· ${percent(съедает[0].sharePct)} оборота`',
    replace: '· ${percent(report.waterfall?.steps[0]?.sharePct ?? null)} оборота`',
    tests: 'все',
  },
  {
    id: 'largest-tie-one-name',
    claim: 'при равенстве назвать в строке только одну ступень',
    mustRedden: СЪЕДАЕТ_ПОРОВНУ,
    file: 'app/page.tsx',
    find: "${съедает.map(подписьСтроки).join(' и ')}",
    replace: '${подписьСтроки(съедает[0])}',
    tests: 'все',
  },
  {
    id: 'largest-without-share',
    claim: 'печатать строку «съедает больше всего» и тогда, когда доли нет',
    mustRedden: СЪЕДАЕТ_БЕЗ_ДОЛИ,
    alsoRedden: [
      { name: ВИД_НОЛЬ, why: 'в её раскладке ступень без доли помечена самой большой, и строка с «нет данных оборота» кладёт слово «оборота» на страницу' },
    ],
    file: 'app/page.tsx',
    find: 'с.largest === true && с.sharePct !== null',
    replace: 'с.largest === true',
    tests: 'все',
  },
  {
    id: 'largest-signal-colour',
    claim: 'покрасить строку «съедает больше всего» сигнальным цветом',
    mustRedden: СЪЕДАЕТ_ЦВЕТ,
    file: 'app/globals.css',
    find: '.waterfall-largest {\n  margin: 0 0 var(--spacingVerticalS);\n}',
    replace: '.waterfall-largest {\n  margin: 0 0 var(--spacingVerticalS);\n  color: var(--colorPaletteRedForeground1);\n}',
    tests: 'все',
  },

  // Шаг 2 — чистая выручка по дням (задача Д-7). Ряд группирует готовую цепочку money по дню заказа;
  // своих выражений денег у него нет. Якорь снаружи — живая проверка: сумма ряда марта 17 277,04 €.
  {
    id: 'daily-own-expression',
    claim: 'посчитать выручку дня своим выражением вместо цепочки money',
    mustRedden: 'сумма ряда по дням — чистая выручка месяца, из той же цепочки money',
    alsoRedden: [
      { name: 'доля дня — от наибольшей по модулю выручки дня, процентами со знаком', why: 'у её строк выручка задана при нулевом обороте; своё выражение даёт нули, и доли меняются' },
      { name: 'края шкалы и подписи оси — ноль и наибольшая выручка дня; столбик дня — от нуля', why: 'наибольшая выручка дня, посчитанная своим выражением, другая — меняется подпись оси' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '  select m.sold_on as day, sum(m.net) as net\n',
    replace: '  select m.sold_on as day, sum(m.gross - m.discount - m.refund_amount) as net\n',
    tests: 'все',
  },
  {
    id: 'daily-empty-day-zero',
    claim: 'отдать день без заказов нулём, а не пустотой',
    mustRedden: 'день без заказов — пусто, а не ноль',
    file: 'lib/metrics/sql.ts',
    find: '       bd.net::text                                                              as net,',
    replace: '       coalesce(bd.net, 0)::text                                                 as net,',
    tests: 'все',
  },
  {
    id: 'daily-empty-day-dropped',
    claim: 'выбросить день без заказов из ряда',
    mustRedden: 'в ряду все дни месяца, по порядку',
    alsoRedden: [
      { name: 'день без заказов — пусто, а не ноль', why: 'первого марта в ряду больше нет' },
      { name: 'подпись дня приходит готовой строкой', why: 'у месяца без заказов ряд становится пустым, и первой подписи нет' },
      { name: 'отчёт несёт ряд из всех дней месяца, прочитанный тем же снимком', why: 'на посеве заказов нет, и ряд отчёта пуст' },
      { name: 'видимые подписи — у каждого пятого дня, начиная с первого', why: 'дни без заказов уходят из ряда вместе со своими подписями' },
      { name: 'месяц без заказов назван признаком, а не пустым графиком', why: 'у месяца без заказов ряд пуст, и признака прочесть не из чего' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '  from days d\n  left join by_day bd on bd.day = d.day\n',
    replace: '  from days d\n  join by_day bd on bd.day = d.day\n',
    tests: 'все',
  },
  {
    id: 'daily-no-nullif',
    claim: 'снять nullif у делителя доли дня',
    mustRedden: 'наибольшая выручка дня ноль — доли пусты, а выручка дня — честный ноль',
    alsoRedden: [
      { name: 'нулевая чистая выручка от реальных строк не роняет отчёт ошибкой деления', why: 'принятая проверка S5: на её раскладке у дня нулевая выручка, и деление на ноль в ряду роняет весь отчёт — ровно то, от чего она сторожит' },
    ],
    file: 'lib/metrics/sql.ts',
    find: 'nullif(max(abs(net)), 0) as top',
    replace: 'max(abs(net)) as top',
    tests: 'все',
  },
  {
    id: 'daily-share-of-signed-max',
    claim: 'делить выручку дня на наибольшую выручку, а не на наибольшую по модулю',
    mustRedden: 'доля дня — от наибольшей по модулю выручки дня, процентами со знаком',
    file: 'lib/metrics/sql.ts',
    find: 'nullif(max(abs(net)), 0) as top',
    replace: 'nullif(max(net), 0) as top',
    tests: 'все',
  },
  {
    id: 'daily-raw-date-label',
    claim: 'отдать подпись дня сырой датой, оставив форматирование разметке',
    mustRedden: 'подпись дня приходит готовой строкой',
    alsoRedden: [
      { name: 'отчёт несёт ряд из всех дней месяца, прочитанный тем же снимком', why: 'она сличает подпись первого дня отчёта — «1 марта»' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '       extract(day from d.day)::int || \x27 \x27 ||\n',
    replace: '       to_char(d.day, \x27YYYY-MM-DD\x27) || \x27\x27 ||\n',
    tests: 'все',
  },
  {
    id: 'daily-not-in-report',
    claim: 'не прочитать ряд по дням в отчёте',
    mustRedden: 'отчёт несёт ряд из всех дней месяца, прочитанный тем же снимком',
    file: 'lib/metrics/report.ts',
    find: '    const dailyResult = await client.query(MONTH_DAILY, [dayParam])\n',
    replace: '    const dailyResult = { rows: [] as Array<Record<string, unknown>> }\n',
    tests: 'все',
  },

  // Шаг 2 — ряд на экране (задача Д-8) и высота его области (П5). Разметка ничего не считает; у
  // каждого дня доступная подпись; день без заказов — словами и пунктиром; месяц без заказов — словами.
  {
    id: 'daily-bar-other-value',
    claim: 'взять для высоты столбика дня не ту долю, что в отчёте',
    mustRedden: 'столбик дня берёт ту же долю и тот же край, что в отчёте',
    file: 'app/page.tsx',
    find: "'--day-size': день.sharePct",
    replace: "'--day-size': день.basePct",
    tests: 'все',
  },
  {
    id: 'daily-aria-dropped',
    claim: 'снять доступную подпись у дней ряда',
    mustRedden: 'у каждого дня доступная подпись с готовой строкой',
    alsoRedden: [
      { name: 'день без заказов — подпись словами, столбика нет, линия отсчёта помечена', why: 'она находит второй день по его доступной подписи' },
    ],
    file: 'app/page.tsx',
    find: "                  data-empty={день.net === null ? 'true' : undefined}\n                  aria-label={",
    replace: "                  data-empty={день.net === null ? 'true' : undefined}\n                  data-label={",
    tests: 'все',
  },
  {
    id: 'daily-empty-day-zero-label',
    claim: 'подписать день без заказов «0,00 €», а не словами',
    mustRedden: 'день без заказов — подпись словами, столбика нет, линия отсчёта помечена',
    file: 'app/page.tsx',
    find: "\x60${день.label}: заказов не было\x60",
    replace: "\x60${день.label}: ${money('0.00')}\x60",
    tests: 'все',
  },
  {
    id: 'daily-ticks-every-day',
    claim: 'подписать под осью каждый день, а не те, что дал отчёт',
    mustRedden: 'видимые подписи дней — ровно те, что дал отчёт',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'в её списке под осью две подписи, «1» и «6», а станет семь' }],
    file: 'app/page.tsx',
    find: '<li key={день.day}>{день.tick}</li>',
    replace: '<li key={день.day}>{день.label}</li>',
    tests: 'все',
  },
  {
    id: 'daily-empty-month-frame',
    claim: 'нарисовать месяцу без заказов пустой график вместо слов',
    mustRedden: 'месяц без заказов — слова «нет данных за месяц», а не пустой график',
    file: 'app/page.tsx',
    find: '{report.daily !== undefined && report.daily.hasOrders && (',
    replace: '{report.daily !== undefined && (',
    tests: 'все',
  },
  {
    id: 'daily-profit-word',
    claim: 'назвать блок ряда прибылью по дням',
    mustRedden: 'в блоке ряда слово «выручка» есть, а слова «прибыль» нет',
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: 'в её списке заголовок блока — «Чистая выручка по дням»' },
      { name: 'ряд рисуется только тогда, когда в отчёте есть его поле', why: 'она узнаёт блок по заголовку' },
    ],
    file: 'app/page.tsx',
    find: '<h2>Чистая выручка по дням</h2>',
    replace: '<h2>Прибыль по дням</h2>',
    tests: 'все',
  },
  {
    id: 'daily-dash-dropped',
    claim: 'снять пунктир под днём без заказов — оставить разрыв неотличимым от нуля по форме',
    mustRedden: 'у дня без заказов линия отсчёта — пунктиром: разрыв отличается от нуля формой',
    file: 'app/globals.css',
    find: "\n.daily-bars li[data-empty='true']::after {\n  border-top-style: dashed;\n}\n",
    replace: '\n',
    tests: 'все',
  },
  {
    id: 'daily-chart-height-foreign',
    claim: 'поставить высоте области ряда длину, не названную исключением',
    mustRedden: 'в таблице стилей нет ни одной величины и ни одного цвета вне набора Fluent 2',
    file: 'app/globals.css',
    find: '  grid-template-rows: 8rem auto;',
    replace: '  grid-template-rows: 9rem auto;',
    tests: 'все',
  },

  // Шаг 3 — окупаемость рекламы (задачи 3 и 10). Определения наши; порог — от вклада, а не от маржи.
  {
    id: 'payback-threshold-from-margin',
    claim: 'считать порог от маржи экрана, а не от вклада',
    mustRedden: 'порог считается от вклада, а не от маржи итога',
    alsoRedden: [
      { name: 'вклад ноль — порога нет, и сказано словами', why: 'порог от маржи есть и тогда, когда вклад ноль' },
      { name: 'вклад отрицателен — порога нет, а не отрицательный порог', why: 'порог от маржи есть и при отрицательном вкладе' },
      { name: 'оборот ноль или реклама ноль — пусто, а не ноль', why: 'порог от маржи есть и при нулевом обороте, когда вклада нет' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '(case when p.contribution > 0 then round(100 / p.contribution, 2) end)::text',
    replace: 'round(100 / nullif((select t.margin_pct::numeric from totals_row t), 0), 2)::text',
    tests: 'все',
  },
  {
    id: 'payback-contribution-with-fixed',
    claim: 'включить постоянные расходы во вклад',
    mustRedden: 'вклад считается без постоянных расходов',
    alsoRedden: [
      { name: 'порог считается от вклада, а не от маржи итога', why: 'порог — 100 ÷ вклад, и вклад стал другим' },
      { name: 'вклад ноль — порога нет, и сказано словами', why: 'вклад с постоянными перестаёт быть нулём' },
      { name: 'вклад отрицателен — порога нет, а не отрицательный порог', why: 'вклад с постоянными — другое отрицательное число' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '(t.net::numeric - t.cogs::numeric - t.fees::numeric) / nullif(t.gross::numeric, 0) * 100',
    replace: '(t.net::numeric - t.cogs::numeric - t.fees::numeric - t.fixed::numeric) / nullif(t.gross::numeric, 0) * 100',
    tests: 'все',
  },
  {
    id: 'payback-contribution-with-ads',
    claim: 'включить рекламу во вклад',
    mustRedden: 'вклад считается без рекламы',
    alsoRedden: [
      { name: 'вклад считается без постоянных расходов', why: 'вклад с рекламой — 36,0 %, а не 48,0 %, на той же раскладке' },
      { name: 'порог считается от вклада, а не от маржи итога', why: 'порог — 100 ÷ вклад, и вклад стал другим' },
      { name: 'вклад ноль — порога нет, и сказано словами', why: 'вклад с рекламой перестаёт быть нулём' },
      { name: 'вклад отрицателен — порога нет, а не отрицательный порог', why: 'вклад с рекламой — другое отрицательное число' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '(t.net::numeric - t.cogs::numeric - t.fees::numeric) / nullif(t.gross::numeric, 0) * 100',
    replace: '(t.net::numeric - t.cogs::numeric - t.fees::numeric - t.ads::numeric) / nullif(t.gross::numeric, 0) * 100',
    tests: 'все',
  },
  {
    id: 'payback-threshold-unguarded',
    claim: 'считать порог и при неположительном вкладе',
    mustRedden: 'вклад ноль — порога нет, и сказано словами',
    alsoRedden: [
      { name: 'вклад отрицателен — порога нет, а не отрицательный порог', why: 'при отрицательном вкладе выходит отрицательный порог' },
      { name: 'нулевая чистая выручка от реальных строк не роняет отчёт ошибкой деления', why: 'принятая проверка S5: на её раскладке вклад ноль, и деление на него роняет весь отчёт — ровно то, от чего она сторожит' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '(case when p.contribution > 0 then round(100 / p.contribution, 2) end)::text',
    replace: 'round(100 / p.contribution, 2)::text',
    tests: 'все',
  },
  {
    id: 'payback-profit-no-nullif',
    claim: 'при нулевой рекламе отдать окупаемость по прибыли нулём, а не пустотой',
    mustRedden: 'оборот ноль или реклама ноль — пусто, а не ноль',
    file: 'lib/metrics/sql.ts',
    find: 'round(p.profit / nullif(p.ads, 0), 2)::text',
    replace: 'coalesce(round(p.profit / nullif(p.ads, 0), 2), 0)::text',
    tests: 'все',
  },
  {
    id: 'payback-label-without-base',
    claim: 'убрать из подписи порога его базу',
    mustRedden: 'подпись порога называет его базу — вклад, а не маржу экрана',
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: 'в её списке подпись порога — с базой' },
      { name: 'вклад стоит числом рядом с порогом', why: 'она находит порог по подписи «Порог окупаемости…» — остаётся, но строка стала другой' },
    ],
    file: 'app/page.tsx',
    find: '<dt>Порог окупаемости — от вклада, а не от маржи</dt>',
    replace: '<dt>Порог окупаемости</dt>',
    tests: 'все',
  },
  {
    id: 'payback-contribution-hidden',
    claim: 'убрать вклад с экрана, оставив порог',
    mustRedden: 'вклад стоит числом рядом с порогом',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'в её списке вклад стоит строкой' }],
    file: 'app/page.tsx',
    find:
      '            <dt>Вклад с евро оборота</dt>\n' +
      '            <dd>{percent(report.payback.contributionPct)}</dd>\n',
    replace: '',
    tests: 'все',
  },
  {
    id: 'payback-ours-unsaid',
    claim: 'не сказать рядом с порогом, что определения наши',
    mustRedden: 'рядом с порогом сказано, что определения наши',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'в её списке строка об определениях' }],
    file: 'app/page.tsx',
    find: '            Вклад и порог — наши определения. Вклад',
    replace: '            Вклад',
    tests: 'все',
  },
  {
    id: 'payback-no-threshold-as-no-data',
    claim: 'печатать «нет данных» там, где порога нет по делу',
    mustRedden: 'порога нет — сказано словами, а не «нет данных» и не отрицательным порогом',
    file: 'app/page.tsx',
    find: '              {report.payback.breakevenNote !== null\n',
    replace: '              {false\n',
    tests: 'все',
  },
  {
    id: 'payback-profit-base-unsaid',
    claim: 'убрать у окупаемости по прибыли фразу о её базе — после постоянных расходов',
    mustRedden: 'у окупаемости по прибыли названа база — после постоянных расходов, и сказано, чем она не порог',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'в её списке фраза стоит строкой под числом' }],
    file: 'app/page.tsx',
    find: '                После постоянных расходов — они от рекламы не зависят, поэтому окупается ли реклама,\n',
    replace: '\n',
    andThen: { find: '                говорит порог, а не это число.\n', replace: '\n' },
    tests: 'все',
  },
  // Шаг 4 — товары. Колонки и строка над таблицей считает SQL от готовых строк таблицы товаров;
  // признак «в минусе» один на подсветку и счётчик; база долей названа на экране.
  {
    id: "items-share-of-net",
    claim: "считать долю строки от суммы чистой выручки строк, а не от суммы их прибыли",
    mustRedden: "доли строк — от суммы прибыли строк, и в сумме дают ровно 100 %",
    file: "lib/metrics/sql.ts",
    find: "round(k.profit / b.total * 100, 1)",
    replace: "round(k.profit / (select sum(r.net::numeric) from items_row r) * 100, 1)",
    tests: "все",
  },
  {
    id: "items-80-ascending",
    claim: "считать 80 % по возрастанию прибыли, а не по убыванию",
    mustRedden: "80 % считаются от суммы прибыли строк, по убыванию прибыли",
    file: "lib/metrics/sql.ts",
    find: "order by r.profit::numeric desc, r.sku",
    replace: "order by r.profit::numeric asc, r.sku",
    tests: "все",
  },
  {
    id: "items-zero-is-loss",
    claim: "считать строку с прибылью ровно ноль убыточной",
    mustRedden: "в минусе — прибыль строго меньше нуля, и счётчик берёт тот же признак",
    file: "lib/metrics/sql.ts",
    find: "       k.profit < 0                                                          as loss,",
    replace: "       k.profit <= 0                                                         as loss,",
    tests: "все",
  },
  {
    id: "items-counter-own-flag",
    claim: "завести счётчику «в минусе» своё условие, отдельное от признака строки",
    mustRedden: "в минусе — прибыль строго меньше нуля, и счётчик берёт тот же признак",
    file: "lib/metrics/sql.ts",
    find: "(count(*) filter (where k.profit < 0) over ())::int",
    replace: "(count(*) filter (where k.profit <= 0) over ())::int",
    tests: "все",
  },
  {
    id: "items-margin-zero",
    claim: "при нулевой чистой выручке строки отдать маржу нулём, а не пустотой",
    mustRedden: "чистая выручка строки ноль — маржа строки пустая",
    file: "lib/metrics/sql.ts",
    find: "round(k.profit / nullif(k.net, 0) * 100, 1)::text",
    replace: "coalesce(round(k.profit / nullif(k.net, 0) * 100, 1), 0)::text",
    tests: "все",
  },
  {
    id: "items-share-when-nonpositive",
    claim: "считать доли и при неположительной сумме прибыли строк",
    mustRedden: "сумма прибыли строк не положительна — доли и 80 % пусты у всех строк разом",
    file: "lib/metrics/sql.ts",
    find: "(case when b.total > 0 then round(k.profit / b.total * 100, 1) end)::text",
    replace: "round(k.profit / nullif(b.total, 0) * 100, 1)::text",
    tests: "все",
  },
  {
    id: "items-share-header-no-base",
    claim: "назвать колонку «Доля в прибыли», без слова «товаров»",
    mustRedden: "заголовок доли называет базу — прибыль товаров, а заголовок маржи — чистую выручку",
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: "в её списке заголовок — «Доля в прибыли товаров»" },
      { name: "новые колонки и строка над таблицей рисуются только при своих полях", why: "она узнаёт колонку по полному заголовку" },
    ],
    file: "app/page.tsx",
    find: "<th>Доля в прибыли товаров</th>",
    replace: "<th>Доля в прибыли</th>",
    tests: "все",
  },
  {
    id: "items-summary-no-base",
    claim: "убрать из строки над таблицей базу долей и её сумму",
    mustRedden: "строка над таблицей называет базу долей и её сумму, и прибыль месяца рядом",
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: "в её списке строка над таблицей — с базой и суммами" },
    ],
    file: "app/page.tsx",
    find: " Прибыль товаров — выручка минус себестоимость, ${money(report.itemsSummary.productsProfit)}; это не прибыль месяца, ${money(report.bottom.profit)}.`",
    replace: "`",
    tests: "все",
  },
  {
    id: "items-loss-from-profit",
    claim: "сравнить прибыль строки с нулём в разметке вместо готового признака",
    mustRedden: "разметка печатает признак «в минусе», который ей дали, а не сравнивает прибыль с нулём",
    file: "app/page.tsx",
    find: "data-loss={item.loss === true ? 'true' : undefined}",
    replace: "data-loss={item.profit.startsWith('-') ? 'true' : undefined}",
    tests: "все",
  },
  {
    id: "items-loss-margin-hidden",
    claim: "подсветить строку в минусе, убрав рядом число маржи",
    mustRedden: "у строки в минусе рядом стоит само число маржи — цвет не единственный признак",
    file: "app/page.tsx",
    find: "{report.itemsSummary !== undefined && <td>{percent(item.marginPct ?? null)}</td>}",
    replace: "{report.itemsSummary !== undefined && item.loss !== true && <td>{percent(item.marginPct ?? null)}</td>}",
    tests: "все",
  },
  {
    id: "items-words-when-nonpositive",
    claim: "печатать «дают … артикулов» и тогда, когда считать 80 % не от чего",
    mustRedden: "сумма прибыли товаров не положительна — строка над таблицей говорит словами",
    file: "app/page.tsx",
    find: "{report.itemsSummary.skusFor80 !== null\n",
    replace: "{true\n",
    tests: "все",
  },

  // П6 — подсветка строки в минусе: свой красный, не токен отказа; в строке нет приглушённого текста.
  {
    id: 'loss-row-refusal-token',
    claim: 'взять для подсветки строки в минусе токен отказа',
    mustRedden: 'подсветка строки в минусе — свой красный, а не токен отказа',
    file: 'app/globals.css',
    find: '  background: var(--colorPaletteRedBackground2);\n',
    replace: '  background: var(--danger-soft);\n',
    tests: 'все',
  },
  {
    id: 'loss-row-muted-text',
    claim: 'оставить в подсвеченной строке приглушённый текст',
    mustRedden: 'в подсвеченной строке нет приглушённого текста — все ячейки основным цветом',
    file: 'app/globals.css',
    find: '  background: var(--colorPaletteRedBackground2);\n  color: var(--colorNeutralForeground1);\n',
    replace: '  background: var(--colorPaletteRedBackground2);\n  color: var(--colorNeutralForeground3);\n',
    tests: 'все',
  },

  // Шаг 5 — доли статей затрат: та же доля, что у ступени водопада; база — оборот, названа у числа.
  {
    id: 'cost-share-other-step',
    claim: 'взять статье долю чужой ступени водопада',
    mustRedden: 'доля статьи — та же, что у её ступени водопада',
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: 'в её списке у себестоимости доля 15,5 %, а придёт доля рекламы' },
      { name: 'полоска статьи берёт ту же долю, что напечатана', why: 'полоска себестоимости получает ту же чужую долю — 16,6 вместо 15,5' },
    ],
    file: 'app/page.tsx',
    find: '<ДоляСтатьи report={report} ключ="cogs" />',
    replace: '<ДоляСтатьи report={report} ключ="ads" />',
    tests: 'все',
  },
  {
    id: 'cost-share-bar-other-value',
    claim: 'взять для полоски статьи не ту долю, что напечатана',
    mustRedden: 'полоска статьи берёт ту же долю, что напечатана',
    file: 'app/page.tsx',
    find: "style={{ '--cost-share': доля } as CSSProperties}",
    replace: "style={{ '--cost-share': '100' } as CSSProperties}",
    tests: 'все',
  },
  {
    id: 'cost-share-no-base',
    claim: 'печатать долю статьи без базы — без слова «оборота»',
    mustRedden: 'у каждой статьи затрат доля названа от оборота',
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: 'в её списке доли статей — «… % оборота»' },
      { name: 'доля статьи — та же, что у её ступени водопада', why: 'она находит доли по слову «оборота»' },
    ],
    file: 'app/page.tsx',
    find: "\x60${percent(доля)} оборота\x60",
    replace: 'percent(доля)',
    tests: 'все',
  },
  {
    id: 'cost-share-zero-bar',
    claim: 'рисовать полоску статьи и тогда, когда доли нет',
    mustRedden: 'оборот ноль — у статей слова, полосок нет',
    file: 'app/page.tsx',
    find: '      {доля !== null && (\n        <span className="cost-bar"',
    replace: '      {(\n        <span className="cost-bar"',
    tests: 'все',
  },
  // После шага 5, проверка раскладки по замечанию владельца: в раскладке переписи край столбика у всех
  // дней с заказами один, а пределы ряда совпадают с пределами водопада. Разметка, взявшая чужое
  // значение, на ней зелена; сломы ниже бьют ровно туда, на раскладке с различными значениями.
  {
    id: 'daily-edge-first-day',
    claim: 'взять для каждого дня край первого дня ряда',
    mustRedden: 'каждый день берёт свой край, а ряд — свои пределы шкалы',
    file: 'app/page.tsx',
    find: "'--day-from': день.basePct",
    replace: "'--day-from': report.daily.days[0].basePct",
    tests: 'все',
  },
  {
    id: 'daily-scale-foreign',
    claim: 'взять для ряда по дням нижний предел шкалы водопада',
    mustRedden: 'каждый день берёт свой край, а ряд — свои пределы шкалы',
    file: 'app/page.tsx',
    find: "'--scale-from': report.daily.scaleLowPct ?? undefined,",
    replace: "'--scale-from': report.waterfall?.scaleLowPct ?? undefined,",
    tests: 'все',
  },
  {
    id: 'waterfall-scale-constant',
    claim: 'поставить водопаду постоянный нижний предел шкалы вместо предела из отчёта',
    mustRedden: 'водопад передаёт шкале свои пределы — ровно те, что дал отчёт',
    file: 'app/page.tsx',
    find: "'--scale-from': report.waterfall.scaleLowPct ?? undefined,",
    replace: "'--scale-from': '0.0',",
    tests: 'все',
  },

  // Шаг 6 — время чтения источников (задачи 5 и 12). Строка готовая из SQL: по UTC, пояс назван;
  // эпоха и отсутствие отметки — пусто; на экране при пустоте слова, а разметка время не трогает.
  {
    id: 'read-at-local-zone',
    claim: 'печатать время чтения в поясе сеанса вместо UTC',
    mustRedden: 'время чтения печатается по UTC и называет пояс',
    alsoRedden: [
      {
        name: 'отчёт несёт время чтения источников, прочитанное тем же снимком',
        why: "сеанс местной базы — в поясе Europe/Minsk (снято `current_setting('TimeZone')`), и настоящий путь печатает время на три часа позже",
      },
    ],
    file: 'lib/metrics/sql.ts',
    find: "to_char(f.raw_seen_at at time zone 'UTC', ",
    replace: 'to_char(f.raw_seen_at, ',
    tests: 'все',
  },
  {
    id: 'read-at-zone-unnamed',
    claim: 'печатать время чтения без названия пояса',
    mustRedden: 'время чтения печатается по UTC и называет пояс',
    alsoRedden: [
      { name: 'отчёт несёт время чтения источников, прочитанное тем же снимком', why: 'она ждёт строку с поясом' },
    ],
    file: 'lib/metrics/sql.ts',
    find: "'YYYY-MM-DD HH24:MI') || ' UTC'",
    replace: "'YYYY-MM-DD HH24:MI')",
    tests: 'все',
  },
  {
    id: 'read-at-epoch',
    claim: 'отдать эпоху как время чтения, когда сырьё было пустым',
    mustRedden: 'отметка-эпоха — это не чтение: пусто, а не 1970 год',
    file: 'lib/metrics/sql.ts',
    find: '\n   where f.raw_seen_at > to_timestamp(0)',
    replace: '',
    tests: 'все',
  },
  {
    id: 'read-at-not-in-report',
    claim: 'не прочитать время чтения в отчёте',
    mustRedden: 'отчёт несёт время чтения источников, прочитанное тем же снимком',
    file: 'lib/metrics/report.ts',
    find: '    const { rows: readAtRows } = await client.query(SOURCES_READ_AT)\n',
    replace: '    const readAtRows: Array<Record<string, unknown>> = []\n',
    tests: 'все',
  },
  {
    id: 'read-at-formatted-in-markup',
    claim: 'форматировать время в разметке вместо того, чтобы печатать готовую строку',
    mustRedden: 'разметка получает время готовой строкой и печатает его как есть',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'в её списке — строка времени, какой её дал отчёт' }],
    file: 'app/page.tsx',
    find: '\x60Источники прочитаны по состоянию на ${report.sourcesReadAt}\x60',
    replace: "\x60Источники прочитаны по состоянию на ${new Date(report.sourcesReadAt).toLocaleString('ru-RU')}\x60",
    tests: 'все',
  },
  {
    id: 'read-at-empty-when-no-mark',
    claim: 'печатать пустую строку, когда отметки о чтении нет',
    mustRedden: 'отметки нет — на экране слова, а не пустая строка и не эпоха',
    file: 'app/page.tsx',
    find: "'Время чтения источников неизвестно: отметки о чтении нет.'",
    replace: "''",
    tests: 'все',
  },
  {
    id: 'read-at-dropped',
    claim: 'снять строку времени чтения с экрана',
    mustRedden: ПЕРЕПИСЬ,
    alsoRedden: [
      { name: 'строка времени рисуется только тогда, когда в отчёте есть её поле', why: 'она ищет строку в шапке' },
      { name: 'разметка получает время готовой строкой и печатает его как есть', why: 'она ищет строку в шапке' },
      { name: 'отметки нет — на экране слова, а не пустая строка и не эпоха', why: 'она ищет строку в шапке' },
    ],
    file: 'app/page.tsx',
    find: '        {report.sourcesReadAt !== undefined && (',
    replace: '        {false && (',
    tests: 'все',
  },

  // Шаг 7 — полоса показателей и дельты (задачи 1 и 8). Дельты считает SQL от показанных значений
  // двух календарных месяцев; нет базы — пусто у всех разом, значения стоят; переход между путями —
  // от данных. Слома «разметка сама считает дельту» нет, и это устройство: прошлых значений в отчёте
  // нет, считать дельту разметке не из чего.
  {
    id: 'deltas-zero-without-base',
    claim: 'отдать ноль вместо пустоты, когда у прошлого месяца нет заказов',
    mustRedden: 'нет предыдущего месяца с заказами — дельты пустые, а не нулевые, у всех четырёх разом',
    alsoRedden: [
      { name: 'база сравнения — предыдущий календарный месяц, даже когда он пуст', why: 'та же пустота на боевой сборке' },
      { name: 'появился предыдущий месяц — дельты считаются; исчез — снова слова', why: 'до появления февраля дельты обязаны быть пусты' },
    ],
    file: 'lib/metrics/sql.ts',
    find: 'case when k.has_orders then k.cur - k.prev end as d',
    replace: 'case when k.has_orders then k.cur - k.prev else 0 end as d',
    tests: 'все',
  },
  {
    id: 'deltas-prev-with-orders',
    claim: 'сравнивать с любым прошлым месяцем с заказами, а не с предыдущим календарным',
    mustRedden: 'база сравнения — предыдущий календарный месяц, даже когда он пуст',
    file: 'lib/metrics/sql.ts',
    find: "where m.month = to_char($1::date - interval '1 month', 'YYYY-MM')\n                   and m.has_orders)",
    replace: "where m.month < to_char($1::date, 'YYYY-MM')\n                   and m.has_orders)",
    tests: 'все',
  },
  {
    id: 'deltas-locked-no-base',
    claim: 'запереть полосу постоянным «нет базы»',
    mustRedden: 'появился предыдущий месяц — дельты считаются; исчез — снова слова',
    alsoRedden: [
      { name: 'прошлый месяц с заказами — дельты считаются от его итогов', why: 'та же база на боевой сборке' },
    ],
    file: 'lib/metrics/sql.ts',
    find: '                   and m.has_orders)                                   as has_orders,',
    replace: '                   and false)                                          as has_orders,',
    tests: 'все',
  },
  {
    id: 'deltas-env-gate',
    claim: 'включать путь с числами переменной среды',
    mustRedden: 'появился предыдущий месяц — дельты считаются; исчез — снова слова',
    file: 'lib/metrics/report.ts',
    find: '        hasBase: deltasResult.rows[0]?.has_base === true,',
    replace: "        hasBase: process.env.NORDIC_PET_DELTAS === 'on' && deltasResult.rows[0]?.has_base === true,",
    tests: 'все',
  },
  {
    id: 'deltas-not-in-report',
    claim: 'не прочитать полосу показателей в отчёте',
    mustRedden: 'отчёт несёт полосу показателей: значения — те же, что в итогах и в водопаде',
    alsoRedden: [
      { name: 'появился предыдущий месяц — дельты считаются; исчез — снова слова', why: 'полоса в отчёте пуста на обоих путях' },
    ],
    file: 'lib/metrics/report.ts',
    find: '    const deltasResult = await client.query(MONTH_DELTAS, [dayParam])\n',
    replace: '    const deltasResult = { rows: [] as Array<Record<string, unknown>> }\n',
    tests: 'все',
  },
  {
    id: 'deltas-margin-relative',
    claim: 'считать дельту маржи в процентах от прошлой, а не в процентных пунктах',
    mustRedden: 'дельта маржи — в процентных пунктах',
    file: 'lib/metrics/sql.ts',
    find: "(2, 'margin',   'pp',  true,  c.margin_pct, c.margin_pct::numeric, p.margin_pct::numeric),",
    replace:
      "(2, 'margin',   'pp',  true,  c.margin_pct, round((c.margin_pct::numeric / nullif(p.margin_pct::numeric, 0) - 1) * 100, 1), 0),",
    tests: 'все',
  },
  {
    id: 'deltas-ad-share-good-flipped',
    claim: 'перевернуть признак «рост — это хорошо» у доли рекламы',
    mustRedden: 'у доли рекламы рост — это плохо, у прибыли — хорошо',
    file: 'lib/metrics/sql.ts',
    find: "(4, 'ad_share', 'pp',  false,",
    replace: "(4, 'ad_share', 'pp',  true,",
    tests: 'все',
  },
  {
    id: 'deltas-ad-share-zero',
    claim: 'отдать ноль вместо пустоты у доли рекламы, когда оборот ноль',
    mustRedden: 'оборот ноль — доля рекламы пустая',
    alsoRedden: [
      {
        name: 'отчёт несёт полосу показателей: значения — те же, что в итогах и в водопаде',
        why: 'в этот момент прогона у марта в местной базе нет фактов, оборот ноль: доля ступени рекламы пуста, а доля полосы под сломом — ноль',
      },
    ],
    file: 'lib/metrics/sql.ts',
    find: '         round(c.ads::numeric / nullif(c.gross::numeric, 0) * 100, 1)::text,',
    replace: '         coalesce(round(c.ads::numeric / nullif(c.gross::numeric, 0) * 100, 1), 0)::text,',
    tests: 'все',
  },
  {
    id: 'deltas-prev-no-ads-zero',
    claim: 'считать долю рекламы прошлого месяца нулём, когда строк рекламы у него нет',
    mustRedden: 'в прошлом месяце нет рекламы — дельта доли рекламы пустая, остальные считаются',
    file: 'lib/metrics/sql.ts',
    find: 'case when s.has_ads then round(p.ads::numeric / nullif(p.gross::numeric, 0) * 100, 1) end)',
    replace: 'round(p.ads::numeric / nullif(p.gross::numeric, 0) * 100, 1))',
    tests: 'все',
  },
  {
    id: 'kpi-value-hidden-without-base',
    claim: 'скрыть значение показателя, когда базы для сравнения нет',
    mustRedden: 'нет базы для сравнения — значения четырёх показателей стоят числами, пуста только дельта',
    file: 'app/page.tsx',
    find: '<span className="kpi-value">{значениеПоказателя(п)}</span>',
    replace: '<span className="kpi-value">{полоса.hasBase ? значениеПоказателя(п) : \'\'}</span>',
    tests: 'все',
  },
  {
    id: 'kpi-no-base-zero',
    claim: 'нарисовать ноль вместо слов, когда базы для сравнения нет',
    mustRedden: 'нет базы — слова, а не ноль',
    alsoRedden: [
      {
        name: 'нет базы для сравнения — значения четырёх показателей стоят числами, пуста только дельта',
        why: 'она ждёт на месте дельты слова',
      },
    ],
    file: 'app/page.tsx',
    find: ': \x60нет базы: в ${полоса.prevMonth} заказов нет\x60',
    replace: ": '+0,00'",
    tests: 'все',
  },
  {
    id: 'kpi-verdict-from-sign',
    claim: 'красить дельту по знаку, а не по признаку из счёта',
    mustRedden: 'разметка печатает дельту и её смысл, которые ей дали, а не выводит смысл из знака',
    file: 'app/page.tsx',
    find: 'data-verdict={п.verdict ?? undefined}',
    replace: "data-verdict={п.delta === null ? undefined : п.delta.startsWith('-') ? 'хуже' : 'лучше'}",
    tests: 'все',
  },
  {
    id: 'kpi-meaning-only-colour',
    claim: 'оставить у дельты только цвет, убрав слово смысла',
    mustRedden: 'смысл дельты назван не только цветом: у каждой строки знак и слово',
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: 'в её списке строки дельт со словом смысла' },
      { name: 'разметка печатает дельту и её смысл, которые ей дали, а не выводит смысл из знака', why: 'она ждёт слово в строке' },
    ],
    file: 'app/page.tsx',
    find: 'к ${полоса.prevMonth} · ${п.verdict}\x60',
    replace: 'к ${полоса.prevMonth}\x60',
    tests: 'все',
  },
  {
    id: 'kpi-label-no-base',
    claim: 'убрать из подписи доли рекламы её базу — оборот',
    mustRedden: 'подписи называют базу отношений, дельты маржи и доли рекламы — в процентных пунктах',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'в её списке подпись с базой' }],
    file: 'app/page.tsx',
    find: "  ad_share: 'Доля рекламы от оборота',",
    replace: "  ad_share: 'Доля рекламы',",
    tests: 'все',
  },
  {
    id: 'kpi-points-as-percent',
    claim: 'печатать дельту маржи и доли рекламы процентами, а не пунктами',
    mustRedden: 'подписи называют базу отношений, дельты маржи и доли рекламы — в процентных пунктах',
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: 'в её списке дельты в пунктах' },
      { name: 'разметка печатает дельту и её смысл, которые ей дали, а не выводит смысл из знака', why: 'она ждёт дельту в пунктах' },
    ],
    file: 'app/page.tsx',
    find: "money(п.delta) : points(п.delta)",
    replace: "money(п.delta) : percent(п.delta)",
    tests: 'все',
  },

  // Ж4 — цвет дельты, решение владельца (вариант Б, 11 сентября 2026 года): «лучше» — зелёный, и
  // зелёный живёт только в строке дельты полосы; «хуже» — свой токен красного (Ж5), не токен отказа; в
  // тёмной теме его значение совпадает с текстом отказа, и роли различает форма — дельта без плашки.
  {
    id: 'green-second-place',
    claim: 'поставить зелёный во второе место на экране',
    mustRedden: 'зелёный — только в строке дельты «лучше» полосы показателей: ровно одно правило',
    file: 'app/globals.css',
    find: '.kpi-value {\n  font-size: var(--fontSizeHero700);',
    replace: '.kpi-value {\n  color: var(--colorPaletteGreenForeground1);\n  font-size: var(--fontSizeHero700);',
    tests: 'все',
  },
  {
    id: 'green-under-another-name',
    claim: 'поставить зелёный во второе место под другим именем величины',
    mustRedden: 'зелёный — только в строке дельты «лучше» полосы показателей: ровно одно правило',
    file: 'app/globals.css',
    find: '  --colorPaletteGreenForeground1: #0e700e;\n',
    replace: '  --colorPaletteGreenForeground1: #0e700e;\n  --kpi-good: var(--colorPaletteGreenForeground1);\n',
    andThen: {
      find: '.kpi-value {\n  font-size: var(--fontSizeHero700);',
      replace: '.kpi-value {\n  color: var(--kpi-good);\n  font-size: var(--fontSizeHero700);',
    },
    tests: 'все',
  },
  {
    id: 'worse-refusal-token',
    claim: 'взять для дельты «хуже» цвет отказа',
    mustRedden: 'дельта «хуже» — свой токен красного, а не токен отказа',
    file: 'app/globals.css',
    find: '  color: var(--colorPaletteRedForeground3);\n}',
    replace: '  color: var(--danger);\n}',
    tests: 'все',
  },
  {
    id: 'worse-as-plaque',
    claim: 'оформить дельту «хуже» плашкой с фоном и рамкой, как отказ',
    mustRedden: 'дельта — простой текст: без фона и рамки, в отличие от плашки отказа',
    file: 'app/globals.css',
    find: '  color: var(--colorPaletteRedForeground3);\n}',
    replace:
      '  color: var(--colorPaletteRedForeground3);\n  background: var(--colorNeutralBackground4);\n  border: var(--strokeWidthThin) solid var(--colorNeutralStroke1);\n}',
    tests: 'все',
  },
  {
    id: 'better-not-green',
    claim: 'снять зелёный у дельты «лучше»',
    mustRedden: 'дельта «лучше» — зелёный',
    alsoRedden: [
      {
        name: 'зелёный — только в строке дельты «лучше» полосы показателей: ровно одно правило',
        why: 'зелёного не остаётся ни в одном правиле, а она ждёт ровно одно',
      },
    ],
    file: 'app/globals.css',
    find: '  color: var(--colorPaletteGreenForeground1);\n}',
    replace: '  color: var(--colorNeutralForeground3);\n}',
    tests: 'все',
  },
  // Шаг вкладок (задачи В-1 — В-8). Вкладка из адреса, «Главное» без вкладки, отказ на незнакомую
  // вкладку; полоса вкладок; разделы — каждый ровно на одной вкладке; перепись по вкладкам; генератор
  // снимков и сторож кадра. Четыре проверки прошлых кусков без прежнего слома получают свой слом здесь.
  {
    id: 'tab-not-read',
    claim: 'не читать вкладку из адреса — всегда первая вкладка',
    mustRedden: 'вкладка из адреса определяет, какие разделы на экране',
    file: 'app/page.tsx',
    find: '  const tabParam = Array.isArray(params.tab) ? params.tab[0] : params.tab\n',
    replace: '  const tabParam = undefined as string | undefined\n',
    tests: 'все',
  },
  {
    id: 'tab-not-read-s6',
    claim: 'не читать вкладку из адреса — проверка S6 «страница отчёта с годной cookie печатает числа»',
    mustRedden: 'страница отчёта с годной cookie печатает числа',
    file: 'app/page.tsx',
    find: '  const tabParam = Array.isArray(params.tab) ? params.tab[0] : params.tab\n',
    replace: '  const tabParam = undefined as string | undefined\n',
    tests: 'все',
  },
  {
    id: 'no-tab-other-default',
    claim: 'адресу без вкладки отдать не первую вкладку',
    mustRedden: 'адрес без вкладки — первая вкладка, и только она',
    file: 'app/page.tsx',
    find: "  const вкладка = tabParam === undefined ? 'glavnoe' : ВКЛАДКИ.find((имя) => имя === tabParam)",
    replace: "  const вкладка = tabParam === undefined ? 'dengi' : ВКЛАДКИ.find((имя) => имя === tabParam)",
    tests: 'все',
  },
  {
    id: 'unknown-tab-silent-first',
    claim: 'незнакомую вкладку молча показать первой',
    mustRedden: 'неизвестная вкладка — отказ словами, а не первая вкладка',
    file: 'app/page.tsx',
    find: "  const вкладка = tabParam === undefined ? 'glavnoe' : ВКЛАДКИ.find((имя) => имя === tabParam)",
    replace: "  const вкладка = tabParam === undefined ? 'glavnoe' : (ВКЛАДКИ.find((имя) => имя === tabParam) ?? 'glavnoe')",
    tests: 'все',
  },
  {
    id: 'tab-last-value',
    claim: 'из двух значений вкладки взять последнее',
    mustRedden: 'из двух значений вкладки берётся первое, как у месяца',
    file: 'app/page.tsx',
    find: '  const tabParam = Array.isArray(params.tab) ? params.tab[0] : params.tab\n',
    replace: '  const tabParam = Array.isArray(params.tab) ? params.tab[params.tab.length - 1] : params.tab\n',
    tests: 'все',
  },
  {
    id: 'unknown-tab-no-links',
    claim: 'отдать незнакомой вкладке отказ без ссылок',
    mustRedden: 'отказ на незнакомую вкладку называет разделы ссылками, и первая — «Главное»',
    file: 'app/page.tsx',
    find: '      <ПолосаВкладок месяц={месяц} текущая={null} />\n',
    replace: '',
    tests: 'все',
  },
  {
    id: 'refresh-leaves-page',
    claim: 'дописать действию кнопки переход на / после работы',
    mustRedden: 'после «Обновить данные» действие не уводит со страницы',
    file: 'app/refresh-action.ts',
    find: '    return await refreshEverything()\n',
    replace: "    await refreshEverything()\n    redirect('/')\n",
    tests: 'все',
  },
  {
    id: 'roas-as-percent',
    claim: 'печатать окупаемость по обороту форматом процента',
    mustRedden: 'окупаемость печатается отношением, а не процентами',
    file: 'app/page.tsx',
    find: '          <dd className="payback-main">{ratio(report.bottom.roasByGross)}</dd>',
    replace: '          <dd className="payback-main">{percent(report.bottom.roasByGross)}</dd>',
    tests: 'все',
  },
  {
    id: 'margin-raw',
    claim: 'печатать маржу «Итога» сырым значением, мимо формата',
    mustRedden: 'нет данных печатается словами, а не как 0 и не как NaN',
    file: 'app/page.tsx',
    find: '          <dd>{percent(report.bottom.marginPct)}</dd>',
    replace: '          <dd>{report.bottom.marginPct}</dd>',
    tests: 'все',
  },
  {
    id: 'no-price-line-dropped',
    claim: 'снять строку «Без цены поставщика»',
    mustRedden: 'экран называет товары без цены поставщика',
    file: 'app/page.tsx',
    find: "          <p>Без цены поставщика (запасные 40%): {report.honesty.skusWithoutPrice.join(', ')}</p>\n",
    replace: '',
    tests: 'все',
  },
  {
    id: 'section-two-tabs',
    claim: 'отдать один раздел двум вкладкам',
    mustRedden: 'каждый раздел — ровно на одной вкладке, порядок вкладок — порядок отчёта',
    file: 'app/page.tsx',
    find: '  return вкладка === текущая ? (',
    replace: "  return вкладка === текущая || (вкладка === 'tovary' && текущая === 'kachestvo') ? (",
    tests: 'все',
  },
  {
    id: 'section-no-tab',
    claim: 'не отдать раздел ни одной вкладке',
    mustRedden: 'каждый раздел — ровно на одной вкладке, порядок вкладок — порядок отчёта',
    file: 'app/page.tsx',
    find: '      <Раздел вкладка="dengi" текущая={tab} className="block bottom-line">',
    replace: '      <Раздел вкладка={\'nigde\' as never} текущая={tab} className="block bottom-line">',
    tests: 'все',
  },
  {
    id: 'tab-link-drops-month',
    claim: 'ссылке вкладки потерять месяц',
    mustRedden: 'ссылки вкладок сохраняют месяц',
    file: 'app/page.tsx',
    find: '              href={месяц === null ? \x60/?tab=${имя}\x60 : \x60/?m=${месяц}&tab=${имя}\x60}',
    replace: '              href={\x60/?tab=${имя}\x60}',
    tests: 'все',
  },
  {
    id: 'month-link-drops-tab',
    claim: 'ссылке месяца потерять вкладку',
    mustRedden: 'ссылки месяцев сохраняют вкладку',
    file: 'app/page.tsx',
    find: "  const хвостВкладки = tab === 'glavnoe' ? '' : \x60&tab=${tab}\x60",
    replace: "  const хвостВкладки = ''",
    tests: 'все',
  },
  {
    id: 'first-tab-root',
    claim: 'ссылке первой вкладки дать адрес корня',
    mustRedden: 'ни одна ссылка вкладок не ведёт на корень',
    file: 'app/page.tsx',
    find: '              href={месяц === null ? \x60/?tab=${имя}\x60 : \x60/?m=${месяц}&tab=${имя}\x60}',
    replace: "              href={имя === 'glavnoe' ? '/' : месяц === null ? \x60/?tab=${имя}\x60 : \x60/?m=${месяц}&tab=${имя}\x60}",
    tests: 'все',
  },
  {
    id: 'current-mark-dropped',
    claim: 'снять признак текущей у текущей вкладки',
    mustRedden: 'у текущей вкладки признак текущей в разметке, у прочих его нет',
    file: 'app/page.tsx',
    find: "              aria-current={имя === текущая ? 'page' : undefined}",
    replace: '              aria-current={undefined}',
    tests: 'все',
  },
  {
    id: 'current-mark-all',
    claim: 'поставить признак текущей всем вкладкам',
    mustRedden: 'у текущей вкладки признак текущей в разметке, у прочих его нет',
    file: 'app/page.tsx',
    find: "              aria-current={имя === текущая ? 'page' : undefined}",
    replace: "              aria-current=\"page\"",
    tests: 'все',
  },
  {
    id: 'fifth-tab',
    claim: 'дописать пятую вкладку',
    mustRedden: 'в полосе вкладок ровно четыре ссылки, в названном порядке',
    file: 'app/page.tsx',
    find: "export const ВКЛАДКИ = ['glavnoe', 'dengi', 'tovary', 'kachestvo'] as const",
    replace: "export const ВКЛАДКИ = ['glavnoe', 'dengi', 'tovary', 'kachestvo', 'pyataya'] as const",
    tests: 'все',
  },
  {
    id: 'tab-removed',
    claim: 'убрать вкладку из приложения',
    mustRedden: ПЕРЕПИСЬ,
    file: 'app/page.tsx',
    find: "export const ВКЛАДКИ = ['glavnoe', 'dengi', 'tovary', 'kachestvo'] as const",
    replace: "export const ВКЛАДКИ = ['glavnoe', 'dengi', 'tovary'] as const",
    tests: 'все',
  },
  {
    id: 'header-first-tab-only',
    claim: 'рисовать шапку только на первой вкладке',
    mustRedden: ПЕРЕПИСЬ,
    file: 'app/page.tsx',
    find: '      <header className="report-head">',
    replace: "      {tab === 'glavnoe' && (<header className=\"report-head\">",
    andThen: { find: '      </header>\n', replace: '      </header>)}\n' },
    tests: 'все',
  },
  {
    id: 'tabs-client-code',
    claim: 'сделать полосу вкладок клиентским кодом',
    mustRedden: 'полоса вкладок без клиентского кода',
    file: 'app/page.tsx',
    find: "import type { CSSProperties, ReactNode } from 'react'\n",
    replace: "'use client'\nimport type { CSSProperties, ReactNode } from 'react'\n",
    tests: 'все',
  },
  {
    id: 'tab-indicator-dropped',
    claim: 'убрать у текущей вкладки полосу-указатель',
    mustRedden: 'у текущей вкладки полоса-указатель толщиной strokeWidthThicker',
    file: 'app/globals.css',
    find: '  height: var(--strokeWidthThicker);\n',
    replace: '',
    tests: 'все',
  },
  {
    id: 'tab-weight-dropped',
    claim: 'убрать у текущей вкладки насыщенность',
    mustRedden: 'у текущей вкладки насыщенность fontWeightSemibold',
    file: 'app/globals.css',
    find: "  color: var(--colorNeutralForeground1);\n  font-weight: var(--fontWeightSemibold);\n}\n\n.tabs a[aria-current='page']::after {",
    replace: "  color: var(--colorNeutralForeground1);\n}\n\n.tabs a[aria-current='page']::after {",
    tests: 'все',
  },
  {
    id: 'tab-indicator-colour-outside',
    claim: 'вписать указателю текущей вкладки цвет вне выписки',
    mustRedden: 'в таблице стилей нет ни одной величины и ни одного цвета вне набора Fluent 2',
    file: 'app/globals.css',
    find: '  background: var(--colorCompoundBrandStroke);\n',
    replace: '  background: #0078d4;\n',
    tests: 'все',
  },
  {
    id: 'census-to-contain',
    claim: 'заменить в переписи сравнение списков на поиск вхождения',
    mustRedden: ПЕРЕПИСЬ,
    file: '__tests__/screen/census.test.tsx',
    find: ')))).toEqual([',
    replace: ')))).toContain([',
    tests: 'все',
  },
  {
    id: 'roas-back-to-bottom',
    claim: 'вернуть окупаемость по обороту в «Итог»',
    mustRedden: ПЕРЕПИСЬ,
    file: 'app/page.tsx',
    find: '          <dt>Окупаемость рекламы (по обороту)</dt>\n          <dd className="payback-main">{ratio(report.bottom.roasByGross)}</dd>\n',
    replace: '',
    andThen: {
      find: '          <dd>{percent(report.bottom.marginPct)}</dd>\n',
      replace:
        '          <dd>{percent(report.bottom.marginPct)}</dd>\n          <dt>Окупаемость рекламы (по обороту)</dt>\n          <dd className="payback-main">{ratio(report.bottom.roasByGross)}</dd>\n',
    },
    tests: 'все',
  },
  {
    id: 'generator-drops-tab-state',
    claim: 'выронить состояние вкладки из описи генератора',
    mustRedden: 'генератор собирает полный набор и сверяет все двадцать страниц',
    file: 'docs/screens/generate.tsx',
    find: "  { имя: 'kachestvo', разметка: вкладка('kachestvo') },\n",
    replace: '',
    tests: 'все',
  },
  {
    id: 'frame-guard-not-called',
    claim: 'не позвать сторожа кадра из генератора',
    mustRedden: 'генератор отказывает, когда нижний край водопада или ряда ниже края кадра',
    file: 'docs/screens/generate.tsx',
    find: '      сверитьКадр(к.файл, низРазделов(браузер, к.файл, страницаКартинки(временный, к), к.ширина, к.высота), к.высота)\n',
    replace: '',
    tests: 'все',
  },
  {
    id: 'frame-guard-body',
    claim: 'выесть тело сторожа кадра',
    mustRedden: 'сторож кадра пропускает край по кадру и отказывает на крае ниже кадра',
    file: 'docs/screens/guards.ts',
    find: '  if (низ <= высота) return\n',
    replace: '  return\n',
    tests: 'все',
  },
]
