import type { Break } from './types.ts'

/**
 * Список сломов куска S13 — один экран: сколько магазин заработал на самом деле.
 *
 * Набор проверок у каждого слома — весь `npm test`. Перепись экрана снимает весь видимый текст по
 * порядку, поэтому слом разметки красит и её — это объявляется у каждого такого слома.
 */

const ПЕРЕПИСЬ = 'перепись экрана: весь видимый текст, по порядку и без единой потери'
const ПЕРЕПИСЬ_ПРИЧИНА = 'перепись снимает весь видимый текст по порядку, а слом его меняет'

export const BREAKS: Break[] = [
  {
    id: 'waterfall-base-gross',
    claim: 'вернуть базу долей каскада к обороту',
    mustRedden: 'доли и края ступеней — от чистой выручки',
    file: 'lib/metrics/sql.ts',
    find: "select case when t.net::numeric > 0 then t.net::numeric end as denom,",
    replace: "select case when t.gross::numeric > 0 then t.gross::numeric end as denom,",
    alsoRedden: [
      { name: 'чистая выручка не положительна — долей и краёв нет, суммы стоят', why: 'при обороте больше нуля доли появляются и при нулевой чистой выручке' },
    ],
    tests: 'все',
  },
  {
    id: 'margin-income-own-expression',
    claim: 'посчитать маржинальный доход из прибыли и постоянных, а не разностью показанных сумм',
    mustRedden: 'маржинальный доход — разность показанных сумм',
    file: 'lib/metrics/sql.ts',
    find: '(5, \'margin_income\', \'итог\',      m.mi,             0::numeric,      m.mi),',
    replace: '(5, \'margin_income\', \'итог\',      t.profit::numeric + t.fixed::numeric, 0::numeric, m.mi),',
    tests: 'все',
  },
  {
    id: 'waterfall-share-says-gross',
    claim: 'назвать базу доли на экране оборотом',
    mustRedden: 'у каждой ступени названа база доли — чистая выручка',
    file: 'app/page.tsx',
    find: '`${percent(ступень.sharePct)} чистой выручки`',
    replace: '`${percent(ступень.sharePct)} оборота`',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: ПЕРЕПИСЬ_ПРИЧИНА }],
    tests: 'все',
  },
  {
    id: 'ads-verdict-strict',
    claim: 'считать окупаемость, равную порогу, неокупившейся',
    mustRedden: 'реклама: окупаемость, равная порогу, — «окупается»',
    file: 'lib/metrics/sql.ts',
    find: "when s.roas >= pb.breakeven_roas::numeric then 'окупается'",
    replace: "when s.roas > pb.breakeven_roas::numeric then 'окупается'",
    tests: 'все',
  },
  {
    id: 'ads-verdict-without-ads',
    claim: 'давать признак рекламы месяцу без строк рекламы',
    mustRedden: 'реклама: строк рекламы нет, окупаемость пуста или оборота нет — признака нет',
    file: 'lib/metrics/sql.ts',
    find: 'select case when not cs.has_ads or s.roas is null or pb.contribution_pct is null then null',
    replace: 'select case when s.roas is null or pb.contribution_pct is null then null',
    tests: 'все',
  },
  {
    id: 'loss-from-unrounded',
    claim: 'считать убыток от неокруглённой доли, а не от показанной',
    mustRedden: 'убыток: ниже 100 % — нет, ровно 100 % показанных — да',
    file: 'lib/metrics/sql.ts',
    find: '(s.mi <= 0 or s.fixed_share >= 100)        as loss,',
    replace: '(s.mi <= 0 or s.fixed / s.mi * 100 >= 100) as loss,',
    tests: 'все',
  },
  {
    id: 'loss-misses-nonpositive-income',
    claim: 'не ставить убыток при неположительном маржинальном доходе',
    mustRedden: 'убыток: маржинальный доход не положителен — доли нет, признак стоит',
    file: 'lib/metrics/sql.ts',
    find: '(s.mi <= 0 or s.fixed_share >= 100)        as loss,',
    replace: 'coalesce(s.fixed_share >= 100, false)     as loss,',
    tests: 'все',
  },
  {
    id: 'approximate-at-hundred',
    claim: 'называть прибыль приблизительной и при доле ровно 100 %',
    mustRedden: 'приблизительная: ниже 100 % — да, ровно 100 % и без доли — нет',
    file: 'lib/metrics/sql.ts',
    find: 'coalesce(s.honest < 100, false)            as approximate',
    replace: 'coalesce(s.honest <= 100, false)           as approximate',
    tests: 'все',
  },
  {
    id: 'mean-over-order-days',
    claim: 'делить на дни с заказами, а не на все дни месяца',
    mustRedden: 'средняя — чистая выручка ÷ все дни месяца, дни без заказов в делителе',
    file: 'lib/metrics/sql.ts',
    find: 'round(sum(bd.net) / count(*), 2)                as avg_net',
    replace: 'round(sum(bd.net) / count(bd.day), 2)          as avg_net',
    tests: 'все',
  },
  {
    id: 'mean-base-word',
    claim: 'писать «дням» при числе дней, оканчивающемся на единицу',
    mustRedden: 'подпись базы средней согласована с числом дней',
    file: 'lib/metrics/sql.ts',
    find: "then ' дню' else ' дням' end || ' месяца'",
    replace: "then ' дням' else ' дням' end || ' месяца'",
    tests: 'все',
  },
  {
    id: 'top-is-six',
    claim: 'класть в первую пятёрку шесть строк',
    mustRedden: 'первая пятёрка — пять лучших по прибыли',
    file: 'lib/metrics/sql.ts',
    find: '(row_number() over (order by k.profit desc, k.sku) <= 5)',
    replace: '(row_number() over (order by k.profit desc, k.sku) <= 6)',
    tests: 'все',
  },
  {
    id: 'top-ties-by-chance',
    claim: 'решать равенство прибыли в пятёрке не артикулом',
    mustRedden: 'первая пятёрка — пять лучших по прибыли',
    file: 'lib/metrics/sql.ts',
    find: '(row_number() over (order by k.profit desc, k.sku) <= 5)',
    replace: '(row_number() over (order by k.profit desc, k.sku desc) <= 5)',
    tests: 'все',
  },
  {
    id: 'items-order-by-net',
    claim: 'упорядочить товары по чистой выручке',
    mustRedden: 'порядок товаров один — валовая прибыль по убыванию',
    file: 'lib/metrics/sql.ts',
    find: 'order by sum(net) - sum(cogs) desc, sku',
    replace: 'order by sum(net) desc, sku',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: 'раскладка переписи идёт через отчёт, а не через запрос; строка объявлена на случай, если прогон покажет иное' }],
    tests: 'все',
  },
  {
    id: 'holes-on-zero',
    claim: 'ставить признак дыр и нулевому виду',
    mustRedden: 'у каждого вида неполноты признак «есть дыры» совпадает с ненулевым счётом',
    file: 'lib/metrics/sql.ts',
    find: 'select kind, count, at, count > 0 as has_holes',
    replace: 'select kind, count, at, count >= 0 as has_holes',
    tests: 'все',
  },
  {
    id: 'kpis-keep-ad-share',
    claim: 'вернуть долю рекламы в полосу показателей',
    mustRedden: 'показателей в полосе три',
    file: 'lib/metrics/sql.ts',
    find: "     (3, 'net',      'eur', true,  c.net,        c.net::numeric,        p.net::numeric)",
    replace: "     (3, 'net',      'eur', true,  c.net,        c.net::numeric,        p.net::numeric),\n     (4, 'ad_share', 'pp',  false, null::text, null::numeric, null::numeric)",
    tests: 'все',
  },
  {
    id: 'command-verdict-swapped',
    claim: 'печатать «месяц в убытке: да» у месяца в плюсе',
    mustRedden: 'в конце вывода — выводы и средняя по дням',
    file: 'scripts/print-metrics.ts',
    find: "announce(`  месяц в убытке: ${f.loss ? 'да' : 'нет'}`)",
    replace: "announce(`  месяц в убытке: ${f.loss ? 'нет' : 'да'}`)",
    tests: 'все',
  },
  {
    id: 'tabs-come-back',
    claim: 'вернуть чтение вкладки из адреса и отказ на незнакомую',
    mustRedden: 'старые адреса со вкладкой и порядком открывают тот же единственный экран',
    file: 'app/page.tsx',
    find: "if ((await проверитьДоступ()) === 'отказать') redirect('/login')",
    replace: "if ((await проверитьДоступ()) === 'отказать') redirect('/login')\n  { const п = await searchParams as { tab?: string }; if (п.tab !== undefined) return <main><p role=\"alert\">Раздела «{п.tab}» в отчёте нет.</p></main> }",
    tests: 'все',
  },
  {
    id: 'money-cards-come-back',
    claim: 'вернуть карточку «Итог»',
    mustRedden: 'карточек «Выручка», «Затраты», «Итог» и блока окупаемости нет',
    file: 'app/page.tsx',
    find: '<section className="block waterfall">',
    replace: '<section className="block waterfall">\n          <section className="block bottom-line"><h2>Итог</h2></section>',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: ПЕРЕПИСЬ_ПРИЧИНА }],
    tests: 'все',
  },
  {
    id: 'no-base-per-number',
    claim: 'вернуть строку «нет базы» к каждому числу',
    mustRedden: 'нет базы — одна строка на блок',
    file: 'app/page.tsx',
    find: '<dt>Чистая выручка</dt>',
    replace: '<dt>Чистая выручка</dt><dd hidden>{полоса !== undefined && !полоса.hasBase ? `в ${полоса.prevMonth} заказов нет` : null}</dd>',
    tests: 'все',
  },
  {
    id: 'approx-always',
    claim: 'ставить пометку «приблизительно» без признака',
    mustRedden: 'пометка «приблизительно» — только по признаку',
    file: 'app/page.tsx',
    find: '{report.findings?.approximate === true && <span className="result-approx">приблизительно</span>}',
    replace: '{<span className="result-approx">приблизительно</span>}',
    tests: 'все',
  },
  {
    id: 'second-hero-size',
    claim: 'завести второе число крупного кегля',
    mustRedden: 'прибыль — единственное число крупного кегля',
    file: 'app/globals.css',
    find: '.result-stats dd {\n  font-size: var(--fontSizeBase400);',
    replace: '.result-stats dd {\n  font-size: var(--fontSizeHero700);',
    tests: 'все',
  },
  {
    id: 'margin-prints-nan',
    claim: 'печатать маржу результата путём, который даёт NaN',
    mustRedden: 'на экране нет NaN',
    file: 'app/page.tsx',
    find: '<dd>{percent(report.bottom.marginPct)}',
    replace: '<dd>{String(Number(\'x\'))}',
    alsoRedden: [
      { name: ПЕРЕПИСЬ, why: ПЕРЕПИСЬ_ПРИЧИНА },
      { name: 'нет базы для сравнения — три числа результата стоят числами', why: 'проверка читает значение маржи в ячейке, а слом его подменяет' },
    ],
    tests: 'все',
  },
  {
    id: 'findings-ads-without-verdict',
    claim: 'рисовать строку рекламы без признака',
    mustRedden: 'строк выводов столько, сколько признаков',
    file: 'app/page.tsx',
    find: "report.findings.adsVerdict !== null &&",
    replace: 'true &&',
    tests: 'все',
  },
  {
    id: 'findings-order',
    claim: 'поставить строку о приблизительной прибыли раньше строки о постоянных',
    mustRedden: 'строк выводов столько, сколько признаков, и в порядке договора',
    file: 'app/page.tsx',
    find: '{строкаРекламы}{строкаПостоянных}{строкаПриблизительной}',
    replace: '{строкаРекламы}{строкаПриблизительной}{строкаПостоянных}',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: ПЕРЕПИСЬ_ПРИЧИНА }],
    tests: 'все',
  },
  {
    id: 'findings-fixed-alarm-below-hundred',
    claim: 'ставить знак тревоги у постоянных ниже 100 %',
    mustRedden: 'постоянные ниже порога тревоги — строка без знака',
    file: 'app/page.tsx',
    find: '`Постоянные расходы ${',
    replace: '`⚠ Постоянные расходы ${',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: ПЕРЕПИСЬ_ПРИЧИНА }],
    tests: 'все',
  },
  {
    id: 'findings-drop-our-mark',
    claim: 'снять пометку «наш счёт» с пояснения порога',
    mustRedden: 'вклад, порог и маржинальный доход помечены «наш счёт»',
    file: 'app/page.tsx',
    find: '`Порог — наш счёт: 100 ÷ вклад с евро оборота, ${',
    replace: '`Порог: 100 ÷ вклад с евро оборота, ${',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: ПЕРЕПИСЬ_ПРИЧИНА }],
    tests: 'все',
  },
  {
    id: 'findings-marginal-claim',
    claim: 'вернуть ложное утверждение об отдаче следующего евро',
    mustRedden: 'совета «масштабировать» и слов о следующем евро как отдаче нет',
    file: 'app/page.tsx',
    find: 'а не отдача от следующего вложенного евро',
    replace: 'следующий евро рекламы приносит больше, чем стоит',
    alsoRedden: [{ name: ПЕРЕПИСЬ, why: ПЕРЕПИСЬ_ПРИЧИНА }],
    tests: 'все',
  },
  {
    id: 'findings-heading-without-flags',
    claim: 'рисовать заголовок «Выводы», когда признаков в отчёте нет',
    mustRedden: 'выводов нет, когда отчёт без признаков',
    file: 'app/page.tsx',
    find: '  if (report.findings === undefined) return null',
    replace: '  if (report.findings === undefined) return <section className="block findings"><h2>Выводы</h2></section>',
    tests: 'все',
  },
]
