import type { Break } from './types.ts'

/**
 * Список сломов куска S5 — семь правил счёта, экран и кнопка «Обновить данные».
 *
 * Перенос таблицы контракта в данные: прогон читает этот же список, и таблица отчёта
 * рождается из вывода прогона, а не из пересказа автора.
 */

export const BREAKS: Break[] = [
  {
    id: "fee-percent-no-div",
    claim: "убрать деление процента на сто",
    mustRedden: "процент хранится пунктами и делится на сто",
    alsoRedden: [
      { name: "комиссия: процент от суммы после скидок плюс фиксированная один раз на заказ", why: "ставка без деления на сто меняет комиссию в любой проверке с ненулевым процентом" },
      { name: "возврат комиссию не пересчитывает", why: "то же" },
      { name: "фиксированная часть берётся по разу на заказ, а не на строку", why: "то же" },
      { name: "пустая фиксированная часть не обнуляет процент", why: "то же" },
      { name: "заказ с разными способами оплаты комиссии не даёт вовсе", why: "то же" },
    ],
    file: "lib/metrics/sql.ts",
    find: "select coalesce(sum(o.amount * fe.percent / 100), 0)",
    replace: "select coalesce(sum(o.amount * fe.percent), 0)",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "fee-per-line",
    claim: "считать комиссию по строке, а не по заказу",
    mustRedden: "фиксированная часть берётся по разу на заказ, а не на строку",
    alsoRedden: [
      { name: "комиссия: процент от суммы после скидок плюс фиксированная один раз на заказ", why: "тот же расчёт по строке вместо заказа задваивает фикс и в этой проверке" },
    ],
    file: "lib/metrics/sql.ts",
    find: "gateway_fees as (\n  select coalesce(sum(o.amount * fe.percent / 100), 0)\n       + coalesce(sum(fe.fixed), 0) as total\n    from paid_orders o\n    join order_gateways g on g.order_id = o.order_id\n    join fact.fees fe on fe.gateway = g.gateway\n   where g.gateways = 1\n),",
    replace: "gateway_fees as (\n  select coalesce(sum((o.gross - o.discount) * fe.percent / 100), 0)\n       + coalesce(sum(fe.fixed), 0) as total\n    from lines o\n    join order_gateways g on g.order_id = o.order_id\n    join fact.fees fe on fe.gateway = g.gateway\n   where g.gateways = 1\n),",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "fee-from-gross",
    claim: "считать комиссию от оборота, а не после скидок",
    mustRedden: "комиссия: процент от суммы после скидок плюс фиксированная один раз на заказ",
    file: "lib/metrics/sql.ts",
    find: "paid_orders as (\n  select order_id, sum(gross - discount) as amount\n    from lines group by order_id\n),",
    replace: "paid_orders as (\n  select order_id, sum(gross) as amount\n    from lines group by order_id\n),",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "fee-after-refund",
    claim: "пересчитать комиссию после возврата",
    mustRedden: "возврат комиссию не пересчитывает",
    file: "lib/metrics/sql.ts",
    find: "paid_orders as (\n  select order_id, sum(gross - discount) as amount\n    from lines group by order_id\n),",
    replace: "paid_orders as (\n  select l.order_id, sum(l.gross - l.discount - coalesce(t.amount, 0)) as amount\n    from lines l\n    left join returned t on t.order_id = l.order_id and t.sku = l.sku\n   group by l.order_id\n),",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "refund-own-month",
    claim: "привязать возврат к месяцу возврата",
    mustRedden: "сдвиг даты возврата на месяц вперёд не меняет ни один итог марта",
    alsoRedden: [
      { name: "возврат уменьшает месяц заказа, а не месяц возврата", why: "тот же перенос привязки возврата к его дате ломает и прямую проверку правила 2" },
    ],
    file: "lib/metrics/sql.ts",
    find: "returned as (\n  select r.order_id, r.sku,\n         sum(r.amount)             as amount,\n         coalesce(sum(r.units), 0) as units\n    from fact.refunds r\n   group by r.order_id, r.sku\n),\ncounted as (\n  select l.order_id, l.sku, l.sold_on, l.gateway, l.units, l.gross, l.discount,",
    replace: "returned as (\n  select r.order_id, r.sku,\n         sum(r.amount)             as amount,\n         coalesce(sum(r.units), 0) as units\n    from fact.refunds r\n    cross join bounds b\n   where r.refund_date >= b.first_day and r.refund_date < b.next_month\n   group by r.order_id, r.sku\n),\ncounted as (\n  select l.order_id, l.sku, l.sold_on, l.gateway, l.units, l.gross, l.discount,",
    tests: "__tests__/metrics/revenue.test.ts",
  },
  {
    id: "month-by-line",
    claim: "брать месяц у строки заказа, а не у заказа целиком",
    mustRedden: "заказ с разошедшимися датами строк идёт в один месяц, и возврат вычитается один раз",
    file: "lib/metrics/sql.ts",
    find: "lines as (\n  select o.order_id, o.sku,\n         min(d.sold_on)               as sold_on,\n         min(o.gateway)               as gateway,\n         sum(o.units)                 as units,\n         sum(o.gross)                 as gross,\n         sum(coalesce(o.discount, 0)) as discount\n    from fact.orders o\n    join order_day d on d.order_id = o.order_id\n    cross join bounds b\n   where d.sold_on >= b.first_day and d.sold_on < b.next_month\n     and o.gross is not null\n   group by o.order_id, o.sku\n),",
    replace: "lines as (\n  select o.order_id, o.sku,\n         min(o.date)                  as sold_on,\n         min(o.gateway)               as gateway,\n         sum(o.units)                 as units,\n         sum(o.gross)                 as gross,\n         sum(coalesce(o.discount, 0)) as discount\n    from fact.orders o\n    join order_day d on d.order_id = o.order_id\n    cross join bounds b\n   where o.date >= b.first_day and o.date < b.next_month\n     and o.gross is not null\n   group by o.order_id, o.sku\n),",
    tests: "__tests__/metrics/revenue.test.ts",
  },
  {
    id: "missing-refund-narrow",
    claim: "считать не попавшим в счёт только возврат, чьей пары нет в заказах",
    mustRedden: "возврат к паре, выпавшей из счёта из-за пустой суммы, тоже назван",
    file: "lib/metrics/sql.ts",
    find: "missing_refunds as (\n  select distinct mr.order_id, mr.sku\n    from month_refunds mr\n    left join lines l on l.order_id = mr.order_id and l.sku = mr.sku\n   where l.order_id is null\n)",
    replace: "missing_refunds as (\n  select distinct mr.order_id, mr.sku\n    from month_refunds mr\n    left join (select distinct order_id, sku from month_orders) o\n      on o.order_id = mr.order_id and o.sku = mr.sku\n   where o.order_id is null\n)",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "no-clamp-units",
    claim: "не обрезать нулём проданные штуки при избыточном возврате",
    mustRedden: "возвращено больше, чем куплено: себестоимость строки ноль, а не отрицательная",
    file: "lib/metrics/sql.ts",
    find: "then greatest(c.units - c.refund_units, 0) * c.price",
    replace: "then (c.units - c.refund_units) * c.price",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "drop-net-real-filter",
    claim: "убрать отдельный счёт чистой выручки строк с настоящей ценой",
    mustRedden: "чистая выручка по строкам с настоящей ценой считается отдельно",
    alsoRedden: [
      { name: "доля честности считается от чистой выручки, а не от оборота", why: "доля честности использует ту же колонку net_real без фильтра по цене" },
    ],
    file: "lib/metrics/sql.ts",
    find: "sum(net) filter (where price is not null) as net_real,",
    replace: "sum(net) as net_real,",
    tests: "все",
  },
  {
    id: "fee-one-formula",
    claim: "складывать части ставки одной формулой",
    mustRedden: "пустой процент ставки не обнуляет фиксированную часть комиссии",
    alsoRedden: [
      { name: "пустая фиксированная часть не обнуляет процент", why: "одна формула вместо раздельных слагаемых обнуляет весь заказ по любой из двух пустых половинок ставки" },
    ],
    file: "lib/metrics/sql.ts",
    find: "gateway_fees as (\n  select coalesce(sum(o.amount * fe.percent / 100), 0)\n       + coalesce(sum(fe.fixed), 0) as total\n    from paid_orders o",
    replace: "gateway_fees as (\n  select coalesce(sum(o.amount * fe.percent / 100 + fe.fixed), 0) as total\n    from paid_orders o",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "zero-rate-not-nullif",
    claim: "не приравнивать нулевой курс к отсутствующему",
    mustRedden: "нулевой курс не рвёт запрос, а считается днём без курса",
    file: "lib/metrics/sql.ts",
    find: "select coalesce(sum(a.spend / nullif(f.usd_per_eur, 0)), 0) as total",
    replace: "select coalesce(sum(a.spend / f.usd_per_eur), 0) as total",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "fee-first-gateway",
    claim: "брать у заказа первый попавшийся способ оплаты",
    mustRedden: "заказ с разными способами оплаты комиссии не даёт вовсе",
    alsoRedden: [
      { name: "заказ, оплаченный двумя способами по одному артикулу, комиссии не даёт и назван", why: "тот же фильтр «ровно один способ оплаты» сторожит оба случая смешанной оплаты" },
    ],
    file: "lib/metrics/sql.ts",
    find: "    join fact.fees fe on fe.gateway = g.gateway\n   where g.gateways = 1\n),",
    replace: "    join fact.fees fe on fe.gateway = g.gateway\n),",
    tests: "все",
  },
  {
    id: "ads-no-month-bound",
    claim: "убрать границы месяца у рекламы",
    mustRedden: "реклама соседнего месяца в счёт не попадает",
    file: "lib/metrics/sql.ts",
    find: "ads_eur as (\n  select coalesce(sum(a.spend / nullif(f.usd_per_eur, 0)), 0) as total\n    from fact.ads a\n    join bounds b on a.date >= b.first_day and a.date < b.next_month\n    join fact.fx f on f.date = a.date\n),",
    replace: "ads_eur as (\n  select coalesce(sum(a.spend / nullif(f.usd_per_eur, 0)), 0) as total\n    from fact.ads a\n    join bounds b on true\n    join fact.fx f on f.date = a.date\n),",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "blind-no-price-counter",
    claim: "ослепить любой счётчик неполноты в постоянный ноль",
    mustRedden: "счётчик «строки продаж без цены поставщика» срабатывает и называет адрес",
    alsoRedden: [
      { name: "счётчик строк без цены поставщика считает строки, а не разные артикулы", why: "тот же счётчик, ослепленный в ноль, используется и в этой проверке" },
    ],
    file: "lib/metrics/sql.ts",
    find: "    select 6, 'строки продаж без цены поставщика',\n           (select count(*) from counted where price is null)::int,\n           array(select distinct sku from counted where price is null order by sku)",
    replace: "    select 6, 'строки продаж без цены поставщика',\n           0::int,\n           array(select distinct sku from counted where price is null order by sku)",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "gateway-count-folded",
    claim: "считать способы оплаты по свёрнутым парам, а не по строкам заказа",
    mustRedden: "заказ, оплаченный двумя способами по одному артикулу, комиссии не даёт и назван",
    file: "lib/metrics/sql.ts",
    find: "order_gateways as (\n  select o.order_id,\n         min(o.gateway)           as gateway,\n         count(distinct o.gateway) as gateways\n    from fact.orders o\n    join order_day d on d.order_id = o.order_id\n    cross join bounds b\n   where d.sold_on >= b.first_day and d.sold_on < b.next_month\n   group by o.order_id\n),",
    replace: "order_gateways as (\n  select order_id,\n         min(gateway)           as gateway,\n         count(distinct gateway) as gateways\n    from lines\n   group by order_id\n),",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "gaps-orders-no-bound",
    claim: "убрать границы месяца у заказов в блоке неполноты",
    mustRedden: "дыра соседнего месяца в счётчики не попадает",
    file: "lib/metrics/sql.ts",
    find: "month_orders as (\n  select o.row_no, o.order_id, o.sku, o.units, o.gross, o.discount, o.gateway, d.sold_on\n    from fact.orders o\n    join order_day d on d.order_id = o.order_id\n    cross join bounds b\n   where d.sold_on >= b.first_day and d.sold_on < b.next_month\n),",
    replace: "month_orders as (\n  select o.row_no, o.order_id, o.sku, o.units, o.gross, o.discount, o.gateway, d.sold_on\n    from fact.orders o\n    join order_day d on d.order_id = o.order_id\n    cross join bounds b\n   where true\n),",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "gaps-ads-no-bound",
    claim: "убрать границы месяца у счётчиков рекламы",
    mustRedden: "дыра рекламы соседнего месяца в счётчики не попадает",
    file: "lib/metrics/sql.ts",
    find: "    union all\n    select 10, 'реклама без суммы',\n           (select count(*) from fact.ads a join bounds b\n              on a.date >= b.first_day and a.date < b.next_month\n             where a.spend is null)::int,\n           array(select a.file_name || ':' || a.row_no::text from fact.ads a join bounds b\n                   on a.date >= b.first_day and a.date < b.next_month\n                  where a.spend is null order by a.file_name, a.row_no)\n    union all\n    select 11, 'дни рекламы без курса',\n           (select count(distinct a.date) from fact.ads a join bounds b\n              on a.date >= b.first_day and a.date < b.next_month\n             where not exists (\n                     select 1 from fact.fx f\n                      where f.date = a.date and f.usd_per_eur is not null and f.usd_per_eur <> 0\n                   ))::int,\n           array(select distinct a.date::text from fact.ads a join bounds b\n                   on a.date >= b.first_day and a.date < b.next_month\n                  where not exists (\n                          select 1 from fact.fx f\n                           where f.date = a.date and f.usd_per_eur is not null and f.usd_per_eur <> 0\n                        )\n                  order by a.date::text)",
    replace: "    union all\n    select 10, 'реклама без суммы',\n           (select count(*) from fact.ads a join bounds b\n              on true\n             where a.spend is null)::int,\n           array(select a.file_name || ':' || a.row_no::text from fact.ads a join bounds b\n                   on true\n                  where a.spend is null order by a.file_name, a.row_no)\n    union all\n    select 11, 'дни рекламы без курса',\n           (select count(distinct a.date) from fact.ads a join bounds b\n              on true\n             where not exists (\n                     select 1 from fact.fx f\n                      where f.date = a.date and f.usd_per_eur is not null and f.usd_per_eur <> 0\n                   ))::int,\n           array(select distinct a.date::text from fact.ads a join bounds b\n                   on true\n                  where not exists (\n                          select 1 from fact.fx f\n                           where f.date = a.date and f.usd_per_eur is not null and f.usd_per_eur <> 0\n                        )\n                  order by a.date::text)",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "items-no-clamp",
    claim: "убрать обрезку штук нулём в таблице товаров",
    mustRedden: "штуки товара не бывают отрицательными на экране",
    file: "lib/metrics/sql.ts",
    find: "sum(greatest(units - refund_units, 0))::text as units,",
    replace: "sum(units - refund_units)::text as units,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "month-shape-permissive",
    claim: "пустить в счёт месяц не в форме ГГГГ-ММ",
    mustRedden: "кривой месяц — отказ нашими словами, а не ошибка базы",
    file: "lib/metrics/report.ts",
    find: "const MONTH_SHAPE = /^\\d{4}-(0[1-9]|1[0-2])$/",
    replace: "const MONTH_SHAPE = /^.*$/",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "no-price-by-sku",
    claim: "считать строки продаж без цены по артикулам, а не по строкам",
    mustRedden: "счётчик строк без цены поставщика считает строки, а не разные артикулы",
    file: "lib/metrics/sql.ts",
    find: "(select count(*) from counted where price is null)::int,",
    replace: "(select count(distinct sku) from counted where price is null)::int,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "cogs-line-round",
    claim: "округлить себестоимость строки на промежутке",
    mustRedden: "три строки по 0,40 × 1,11 = 0,444 каждая: сумма остатков округляется один раз",
    file: "lib/metrics/sql.ts",
    find: "else 0.40 * (c.gross - c.discount - c.refund_amount)",
    replace: "else round(0.40 * (c.gross - c.discount - c.refund_amount), 2)",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "net-no-refund",
    claim: "не вычитать возвраты из чистой выручки",
    mustRedden: "чистая выручка = оборот − скидки − возвраты",
    alsoRedden: [
      { name: "возврат уменьшает месяц заказа, а не месяц возврата", why: "та же чистая выручка без вычета возврата используется и здесь" },
      { name: "сдвиг даты возврата на месяц вперёд не меняет ни один итог марта", why: "то же" },
      { name: "заказ с разошедшимися датами строк идёт в один месяц, и возврат вычитается один раз", why: "то же" },
    ],
    file: "lib/metrics/sql.ts",
    find: "c.gross - c.discount - c.refund_amount as net,",
    replace: "c.gross - c.discount as net,",
    tests: "__tests__/metrics/revenue.test.ts",
  },
  {
    id: "net-no-discount",
    claim: "не вычитать скидки",
    mustRedden: "чистая выручка = оборот − скидки − возвраты",
    file: "lib/metrics/sql.ts",
    find: "c.gross - c.discount - c.refund_amount as net,",
    replace: "c.gross - c.refund_amount as net,",
    tests: "__tests__/metrics/revenue.test.ts",
  },
  {
    id: "price-ignore-date",
    claim: "брать цену без учёта даты продажи",
    mustRedden: "цена берётся действовавшая на дату продажи, а не последняя",
    alsoRedden: [
      { name: "цена, начинающая действовать после продажи, не берётся", why: "снятие условия «не позже даты продажи» пропускает и цену из будущего" },
    ],
    file: "lib/metrics/sql.ts",
    find: "(select c.cost\n            from fact.costs c\n           where c.sku = l.sku and c.valid_from <= l.sold_on\n           order by c.valid_from desc\n           limit 1) as price\n    from lines l\n    left join returned t on t.order_id = l.order_id and t.sku = l.sku\n),\nmoney as (",
    replace: "(select c.cost\n            from fact.costs c\n           where c.sku = l.sku\n           order by c.valid_from desc\n           limit 1) as price\n    from lines l\n    left join returned t on t.order_id = l.order_id and t.sku = l.sku\n),\nmoney as (",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "price-latest-overall",
    claim: "брать самую позднюю цену вместо действующей",
    mustRedden: "цена берётся действовавшая на дату продажи, а не последняя",
    alsoRedden: [
      { name: "цена, начинающая действовать после продажи, не берётся", why: "снятие условия «не позже даты продажи» пропускает и цену из будущего" },
    ],
    file: "lib/metrics/sql.ts",
    find: "(select c.cost\n            from fact.costs c\n           where c.sku = l.sku and c.valid_from <= l.sold_on\n           order by c.valid_from desc\n           limit 1) as price\n    from lines l\n    left join returned t on t.order_id = l.order_id and t.sku = l.sku\n),\nmoney as (",
    replace: "(select c.cost\n            from fact.costs c\n           where c.sku = l.sku and c.valid_from is not null\n           order by c.valid_from desc\n           limit 1) as price\n    from lines l\n    left join returned t on t.order_id = l.order_id and t.sku = l.sku\n),\nmoney as (",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "price-fallback-to-cancelled",
    claim: "откатываться к отменённой цене при пустой действующей",
    mustRedden: "пустая цена у действующей строки не откатывается к отменённой",
    file: "lib/metrics/sql.ts",
    find: "(select c.cost\n            from fact.costs c\n           where c.sku = l.sku and c.valid_from <= l.sold_on\n           order by c.valid_from desc\n           limit 1) as price\n    from lines l\n    left join returned t on t.order_id = l.order_id and t.sku = l.sku\n),\nmoney as (",
    replace: "(select c.cost\n            from fact.costs c\n           where c.sku = l.sku and c.valid_from <= l.sold_on and c.cost is not null\n           order by c.valid_from desc\n           limit 1) as price\n    from lines l\n    left join returned t on t.order_id = l.order_id and t.sku = l.sku\n),\nmoney as (",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "cogs-no-refund-deduction",
    claim: "не снимать себестоимость возвращённых штук",
    mustRedden: "возврат снимает себестоимость возвращённых штук",
    alsoRedden: [
      { name: "возвращено больше, чем куплено: себестоимость строки ноль, а не отрицательная", why: "тот же множитель без вычета возвращённых штук меняет и этот случай" },
      { name: "товары отсортированы по чистой выручке убыванием, штуки — за вычетом возвращённых", why: "себестоимость строки с ценой — общий механизм для итогов и для таблицы товаров" },
      { name: "возврат без суммы штуки снимает, хотя выручку не уменьшает", why: "то же: множитель без вычета возвращённых штук меняет и эту проверку" },
    ],
    file: "lib/metrics/sql.ts",
    find: "then greatest(c.units - c.refund_units, 0) * c.price",
    replace: "then greatest(c.units, 0) * c.price",
    tests: "все",
  },
  {
    id: "rule5-twice",
    claim: "применить правило 5 к строке без цены поставщика",
    mustRedden: "правило 5 не применяется второй раз к товару без цены",
    file: "lib/metrics/sql.ts",
    find: "else 0.40 * (c.gross - c.discount - c.refund_amount)",
    replace: "else 0.40 * (c.gross - c.discount - c.refund_amount - c.refund_amount)",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "fallback-from-gross",
    claim: "считать запасные 40% от оборота, а не от чистой выручки",
    mustRedden: "товар без цены поставщика считается по 40% чистой выручки строки",
    alsoRedden: [
      { name: "правило 5 не применяется второй раз к товару без цены", why: "та же замена чистой выручки оборотом видна и в проверке с возвратом" },
    ],
    file: "lib/metrics/sql.ts",
    find: "else 0.40 * (c.gross - c.discount - c.refund_amount)",
    replace: "else 0.40 * c.gross",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "fallback-month-wide",
    claim: "считать 40% от чистой выручки всего месяца, а не строки",
    mustRedden: "запасной процент берётся от строки, а не от чистой выручки всего месяца",
    alsoRedden: [
      { name: "товары отсортированы по чистой выручке убыванием, штуки — за вычетом возвращённых", why: "тот же оконный расчёт по всему месяцу вместо строки виден и в таблице товаров" },
      { name: "три строки по 0,40 × 1,11 = 0,444 каждая: сумма остатков округляется один раз", why: "три строки без цены в одном месяце — ровно тот случай, где оконная сумма подменяет строку" },
    ],
    file: "lib/metrics/sql.ts",
    find: "else 0.40 * (c.gross - c.discount - c.refund_amount)",
    replace: "else 0.40 * sum(c.gross - c.discount - c.refund_amount) over ()",
    tests: "все",
  },
  {
    id: "ads-multiply-rate",
    claim: "умножать рекламу на курс вместо деления",
    mustRedden: "реклама переводится делением на курс своего дня",
    alsoRedden: [
      { name: "у каждого дня свой курс, а не курс конца месяца", why: "общий расчёт евро по рекламе меняется во всех проверках этого блока" },
      { name: "нулевой курс не рвёт запрос, а считается днём без курса", why: "то же" },
      { name: "пустой курс уносит расход своего дня и только своего", why: "то же" },
    ],
    file: "lib/metrics/sql.ts",
    find: "select coalesce(sum(a.spend / nullif(f.usd_per_eur, 0)), 0) as total",
    replace: "select coalesce(sum(a.spend * f.usd_per_eur), 0) as total",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "ads-month-end-rate",
    claim: "брать курс конца месяца для всей рекламы",
    mustRedden: "у каждого дня свой курс, а не курс конца месяца",
    alsoRedden: [
      { name: "реклама переводится делением на курс своего дня", why: "общий расчёт евро по рекламе меняется во всех проверках этого блока" },
      { name: "нулевой курс не рвёт запрос, а считается днём без курса", why: "то же" },
      { name: "пустой курс уносит расход своего дня и только своего", why: "то же" },
    ],
    file: "lib/metrics/sql.ts",
    find: "    join bounds b on a.date >= b.first_day and a.date < b.next_month\n    join fact.fx f on f.date = a.date\n),",
    replace: "    join bounds b on a.date >= b.first_day and a.date < b.next_month\n    join fact.fx f on f.date = (b.next_month - interval '1 day')::date\n),",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "ads-today-rate",
    claim: "брать сегодняшний курс",
    mustRedden: "у каждого дня свой курс, а не курс конца месяца",
    alsoRedden: [
      { name: "реклама переводится делением на курс своего дня", why: "общий расчёт евро по рекламе меняется во всех проверках этого блока" },
      { name: "нулевой курс не рвёт запрос, а считается днём без курса", why: "то же" },
      { name: "пустой курс уносит расход своего дня и только своего", why: "то же" },
    ],
    file: "lib/metrics/sql.ts",
    find: "    join bounds b on a.date >= b.first_day and a.date < b.next_month\n    join fact.fx f on f.date = a.date\n),",
    replace: "    join bounds b on a.date >= b.first_day and a.date < b.next_month\n    join fact.fx f on f.date = current_date\n),",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "roas-from-net",
    claim: "считать окупаемость от чистой выручки",
    mustRedden: "окупаемость считается от оборота, а не от чистой выручки",
    file: "lib/metrics/sql.ts",
    find: "round(coalesce(gross, 0) / nullif(ads, 0), 2)::text                     as roas_by_gross,",
    replace: "round(coalesce(net, 0) / nullif(ads, 0), 2)::text                     as roas_by_gross,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "roas-label-removed",
    claim: "убрать подпись «по обороту»",
    mustRedden: "окупаемость подписана словом «по обороту»",
    file: "app/page.tsx",
    find: "<dt>окупаемость рекламы (по обороту)</dt>",
    replace: "<dt>окупаемость рекламы</dt>",
    tests: "__tests__/metrics/screen.test.tsx",
  },
  {
    id: "roas-percent-sign",
    claim: "печатать окупаемость со знаком процента",
    // Найдено на приёмке: и экран, и команда печатали окупаемость через `percent`, и
    // «оборот больше рекламы в 4,23 раза» выходило как «4,23 %» — реклама будто бы
    // вернула четыре процента, смысл наоборот. Слом бьёт в общую точку обоих мест —
    // саму функцию формата, — а не в один вызов: правкой одного файла подменяется
    // знак у окупаемости и на экране, и в команде разом.
    mustRedden: "окупаемость: разряды, запятая, знак × после числа",
    alsoRedden: [
      { name: "формат окупаемости ничего не округляет", why: "тот же знак проверяется вторым числом в соседней проверке того же файла" },
    ],
    file: "lib/metrics/format.ts",
    find: "  return `${groupDigits(v)} ×`\n}",
    replace: "  return `${groupDigits(v)} %`\n}",
    tests: "__tests__/metrics/format.test.ts",
  },
  {
    id: "margin-from-gross",
    claim: "считать маржу от оборота",
    mustRedden: "маржа — прибыль ÷ чистую выручку",
    file: "lib/metrics/sql.ts",
    find: "       round((coalesce(net,0) - coalesce(cogs,0) - ads - fees - fixed)\n             / nullif(net, 0) * 100, 1)::text                                  as margin_pct,",
    replace: "       round((coalesce(net,0) - coalesce(cogs,0) - ads - fees)\n             / nullif(net, 0) * 100, 1)::text                                  as margin_pct,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "honest-from-gross",
    claim: "считать долю честности от оборота",
    mustRedden: "доля честности считается от чистой выручки, а не от оборота",
    alsoRedden: [
      { name: "нулевая чистая выручка от реальных строк не роняет отчёт ошибкой деления", why: "та же подмена знаменателя оборотом видна и здесь: делитель больше не ноль" },
    ],
    file: "lib/metrics/sql.ts",
    find: "round(coalesce(net_real, 0) / nullif(net, 0) * 100, 1)::text            as honest_pct",
    replace: "round(coalesce(net_real, 0) / nullif(gross, 0) * 100, 1)::text            as honest_pct",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "honest-label-removed",
    claim: "убрать подпись «от чистой выручки»",
    mustRedden: "доля подписана словами «от чистой выручки»",
    file: "app/page.tsx",
    find: "Посчитано по настоящей цене поставщика (доля от чистой выручки):{' '}",
    replace: "Посчитано по настоящей цене поставщика:{' '}",
    tests: "__tests__/metrics/screen.test.tsx",
  },
  {
    id: "honest-by-units",
    claim: "считать долю честности по штукам, а не по деньгам",
    mustRedden: "доля честности считается от чистой выручки, а не от оборота",
    file: "lib/metrics/sql.ts",
    find: "sum(net) filter (where price is not null) as net_real,",
    replace: "sum(net) filter (where price is not null) as net_real,\n         sum(greatest(units - refund_units, 0)) filter (where price is not null) as units_real,\n         sum(greatest(units - refund_units, 0)) as units_total,",
    andThen: { find: "round(coalesce(net_real, 0) / nullif(net, 0) * 100, 1)::text            as honest_pct", replace: "round(coalesce(units_real, 0) / nullif(units_total, 0) * 100, 1)::text            as honest_pct" },
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "honest-includes-no-price",
    claim: "включить товар без цены в долю честности",
    mustRedden: "доля честности считается от чистой выручки, а не от оборота",
    alsoRedden: [
      { name: "чистая выручка по строкам с настоящей ценой считается отдельно", why: "та же колонка net_real без фильтра по цене используется в обеих проверках" },
    ],
    file: "lib/metrics/sql.ts",
    find: "sum(net) filter (where price is not null) as net_real,",
    replace: "sum(net) as net_real,",
    tests: "все",
  },
  {
    id: "opex-all-months",
    claim: "взять постоянные расходы за все месяцы",
    mustRedden: "постоянные расходы берутся за свой месяц, пустая сумма не считается нулём молча",
    file: "lib/metrics/sql.ts",
    find: "select coalesce(sum(x.amount), 0) as total\n    from fact.opex x, bounds b\n   where x.month = b.first_day",
    replace: "select coalesce(sum(x.amount), 0) as total\n    from fact.opex x, bounds b",
    tests: "__tests__/metrics/spend.test.ts",
  },
  {
    id: "gap-discount-blind",
    claim: "подставить ноль вместо пустой скидки без называния",
    mustRedden: "счётчик «скидки» срабатывает и называет адрес",
    alsoRedden: [
      { name: "каждая найденная дыра называет адрес", why: "тот же счётчик скидок используется в обеих проверках" },
    ],
    file: "lib/metrics/sql.ts",
    find: "    select 1 as ord, 'скидки' as kind,\n           (select count(*) from month_orders where discount is null)::int as count,\n           array(select row_no::text from month_orders where discount is null order by row_no) as at",
    replace: "    select 1 as ord, 'скидки' as kind,\n           (select count(*) from month_orders where false)::int as count,\n           array(select row_no::text from month_orders where false order by row_no) as at",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "cut-null-by-pair",
    claim: "отсеивать строки без суммы после свёртки пары, а не по строке источника",
    mustRedden: "в паре с пустой суммой пустая строка уносит свою скидку, а сосед остаётся",
    alsoRedden: [
      { name: "строка без суммы не даёт ни оборота, ни скидки", why: "тот же отсев по свёрнутой сумме, а не по строке источника, протекает и в этом случае" },
    ],
    file: "lib/metrics/sql.ts",
    find: "     and o.gross is not null\n",
    replace: "",
    tests: "__tests__/metrics/revenue.test.ts",
  },
  {
    id: "gap-opex-blind",
    claim: "подставить ноль вместо пустой строки расходов",
    mustRedden: "счётчик «постоянные расходы без суммы» срабатывает и называет адрес",
    file: "lib/metrics/sql.ts",
    find: "    select 9, 'постоянные расходы без суммы',\n           (select count(*) from fact.opex x, bounds b\n             where x.month = b.first_day and x.amount is null)::int,\n           array(select category from fact.opex x, bounds b\n                  where x.month = b.first_day and x.amount is null order by category)",
    replace: "    select 9, 'постоянные расходы без суммы',\n           (select count(*) from fact.opex x, bounds b\n             where x.month = b.first_day and false)::int,\n           array(select category from fact.opex x, bounds b\n                  where x.month = b.first_day and false order by category)",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "gap-refund-amount-blind",
    claim: "подставить ноль вместо пустой суммы возврата",
    mustRedden: "счётчик «возвраты без суммы» срабатывает и называет адрес",
    file: "lib/metrics/sql.ts",
    find: "    select 3, 'возвраты без суммы',\n           (select count(*) from month_refunds where amount is null)::int,\n           array(select row_no::text from month_refunds where amount is null order by row_no)",
    replace: "    select 3, 'возвраты без суммы',\n           (select count(*) from month_refunds where false)::int,\n           array(select row_no::text from month_refunds where false order by row_no)",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "gap-price-blind",
    claim: "подставить ноль вместо пустой цены поставщика",
    mustRedden: "счётчик «строки продаж без цены поставщика» срабатывает и называет адрес",
    alsoRedden: [
      { name: "доля честности считается от чистой выручки, а не от оборота", why: "тот же список артикулов без цены используется и в проверке доли честности" },
      { name: "счётчик строк без цены поставщика считает строки, а не разные артикулы", why: "тот же ослепленный счётчик используется и в этой проверке" },
    ],
    file: "lib/metrics/sql.ts",
    find: "    select 6, 'строки продаж без цены поставщика',\n           (select count(*) from counted where price is null)::int,\n           array(select distinct sku from counted where price is null order by sku)",
    replace: "    select 6, 'строки продаж без цены поставщика',\n           (select count(*) from counted where false)::int,\n           array(select distinct sku from counted where false order by sku)",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "gaps-only-when-nonzero",
    claim: "печатать блок неполноты, только когда дыры есть",
    mustRedden: "блок неполноты виден, даже когда все нули",
    file: "app/page.tsx",
    find: "        <ul>\n          {report.gaps.map((gap) => (",
    replace: "        <ul>\n          {report.gaps.some((g) => g.count > 0) && report.gaps.map((gap) => (",
    tests: "__tests__/metrics/screen.test.tsx",
  },
  {
    id: "gaps-no-address",
    claim: "убрать адреса из блока неполноты",
    mustRedden: "блок неполноты называет адрес у каждой ненулевой дыры",
    file: "app/page.tsx",
    find: "{gap.at.length > 0 ? ` (${gap.at.join(', ')})` : ''}",
    replace: "''",
    tests: "__tests__/metrics/screen.test.tsx",
  },
  {
    id: "orphan-refund-counted",
    claim: "учесть возврат, чьего заказа нет в заказах",
    mustRedden: "возврат, не попавший в счёт, назван — и когда пары нет, и когда пара выпала",
    file: "lib/metrics/sql.ts",
    find: "sum(net) as net,",
    replace: "sum(net) - coalesce((select sum(r.amount) from fact.refunds r\n         left join lines l2 on l2.order_id = r.order_id and l2.sku = r.sku\n        where l2.order_id is null), 0) as net,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "honest-zero-net",
    claim: "считать долю при нулевой чистой выручке",
    mustRedden: "нулевая чистая выручка от реальных строк не роняет отчёт ошибкой деления",
    file: "lib/metrics/sql.ts",
    find: "round(coalesce(net_real, 0) / nullif(net, 0) * 100, 1)::text            as honest_pct",
    replace: "round(coalesce(net_real, 0) / net * 100, 1)::text            as honest_pct",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "margin-zero-net",
    claim: "считать маржу при нулевой чистой выручке",
    mustRedden: "нулевая чистая выручка от реальных строк не роняет отчёт ошибкой деления",
    file: "lib/metrics/sql.ts",
    find: "             / nullif(net, 0) * 100, 1)::text                                  as margin_pct,",
    replace: "             / net * 100, 1)::text                                  as margin_pct,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "roas-zero-ads",
    claim: "считать окупаемость при нулевой рекламе",
    mustRedden: "при нулевой рекламе окупаемость — нет данных",
    file: "lib/metrics/sql.ts",
    find: "round(coalesce(gross, 0) / nullif(ads, 0), 2)::text                     as roas_by_gross,",
    replace: "round(coalesce(gross, 0) / greatest(ads, 0.01), 2)::text                     as roas_by_gross,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "money-to-number",
    claim: "превратить деньги в число в слое метрик",
    mustRedden: "слой метрик не превращает деньги в число",
    file: "lib/metrics/format.ts",
    find: "return `${groupDigits(v)} €`",
    replace: "return `${groupDigits(Number(v).toFixed(2))} €`",
    tests: "__tests__/metrics/no-float-money.test.ts",
  },
  {
    id: "intermediate-round",
    claim: "округлить промежуточные величины",
    mustRedden: "три строки по 0,40 × 1,11 = 0,444 каждая: сумма остатков округляется один раз",
    file: "lib/metrics/sql.ts",
    find: "then greatest(c.units - c.refund_units, 0) * c.price\n              else 0.40 * (c.gross - c.discount - c.refund_amount)",
    replace: "then round(greatest(c.units - c.refund_units, 0) * c.price, 2)\n              else round(0.40 * (c.gross - c.discount - c.refund_amount), 2)",
    tests: "__tests__/metrics/cogs.test.ts",
  },
  {
    id: "ads-round-per-line",
    claim: "округлить рекламу построчно",
    mustRedden: "реклама трёх дней с одинаковым неровным курсом не теряет копейку на сумме",
    file: "lib/metrics/sql.ts",
    find: "select coalesce(sum(a.spend / nullif(f.usd_per_eur, 0)), 0) as total",
    replace: "select coalesce(sum(round(a.spend / nullif(f.usd_per_eur, 0), 2)), 0) as total",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "pair-max-not-sum",
    claim: "брать одну строку пары «заказ + артикул» вместо суммы",
    mustRedden: "две строки одной пары «заказ + артикул» складываются, а не теряются",
    alsoRedden: [
      { name: "заказ с разошедшимися датами строк идёт в один месяц, и возврат вычитается один раз", why: "та же свёртка по max вместо sum видна и в этом случае: строки той же пары складываются там тоже" },
    ],
    file: "lib/metrics/sql.ts",
    find: "         sum(o.units)                 as units,\n         sum(o.gross)                 as gross,\n         sum(coalesce(o.discount, 0)) as discount",
    replace: "         max(o.units)                 as units,\n         max(o.gross)                 as gross,\n         max(coalesce(o.discount, 0)) as discount",
    tests: "__tests__/metrics/revenue.test.ts",
  },
  {
    id: "snapshot-not-repeatable",
    claim: "открыть транзакцию отчёта не на повторяемом чтении",
    mustRedden: "открывается на повторяемом чтении и только на чтение",
    alsoRedden: [
      { name: "на настоящей базе без единого довода: запись внутри снимка невозможна", why: "снятая read only вместе с уровнем изоляции снимает и запрет записи внутри снимка" },
    ],
    file: "lib/metrics/report.ts",
    find: "await guarded.query('begin isolation level repeatable read read only')",
    replace: "await guarded.query('begin')",
    tests: "__tests__/metrics/snapshot.test.ts",
  },
  {
    id: "snapshot-not-read-only",
    claim: "убрать `read only` у транзакции отчёта",
    mustRedden: "на настоящей базе без единого довода: запись внутри снимка невозможна",
    alsoRedden: [
      { name: "открывается на повторяемом чтении и только на чтение", why: "тот же текст команды begin проверяется дословно в обеих проверках" },
    ],
    file: "lib/metrics/report.ts",
    find: "await guarded.query('begin isolation level repeatable read read only')",
    replace: "await guarded.query('begin isolation level repeatable read')",
    tests: "__tests__/metrics/snapshot.test.ts",
  },
  {
    id: "screen-computes-profit",
    claim: "посчитать что-нибудь в разметке страницы",
    mustRedden: "экран печатает поля отчёта, а не свои числа",
    file: "app/page.tsx",
    find: "          <dt>Прибыль</dt>\n          <dd>{money(report.bottom.profit)}</dd>",
    replace: "          <dt>Прибыль</dt>\n          <dd>{money(String(Number(report.revenue.net) - Number(report.costs.cogs) - Number(report.costs.ads) - Number(report.costs.fees) - Number(report.costs.fixed)))}</dd>",
    tests: "__tests__/metrics/screen.test.tsx",
  },
  {
    id: "screen-diverges-from-report",
    claim: "разойтись числами экрана и отчёта",
    mustRedden: "экран печатает поля отчёта, а не свои числа",
    file: "app/page.tsx",
    find: "          <dt>Скидки</dt>\n          <dd>{money(report.revenue.discounts)}</dd>",
    replace: "          <dt>Скидки</dt>\n          <dd>{money(report.revenue.gross)}</dd>",
    tests: "__tests__/metrics/screen.test.tsx",
  },
  {
    id: "named-query-allowed",
    claim: "передать запрос объектом с полем `name`",
    mustRedden: "именованный запрос — отказ нашими словами",
    file: "lib/metrics/report.ts",
    find: "if (typeof sql !== 'string') {",
    replace: "if (false) {",
    tests: "__tests__/metrics/snapshot.test.ts",
  },
  {
    id: "first-arg-check-weak",
    claim: "убрать проверку первого довода запроса",
    mustRedden: "именованный запрос — отказ нашими словами",
    file: "lib/metrics/report.ts",
    find: "if (typeof sql !== 'string') {",
    replace: "if (sql === undefined) {",
    tests: "__tests__/metrics/snapshot.test.ts",
  },
  {
    id: "swallow-facts-refusal",
    claim: "проглотить отказ разбора после удачных загрузок",
    mustRedden: "отказ разбора после удачных загрузок называет щель",
    alsoRedden: [
      { name: "текст отказа несёт причину, а не только шаг", why: "проглоченный отказ разбора не несёт причину и в этой проверке" },
    ],
    file: "lib/metrics/refresh.ts",
    find: "  announce('разбор')\n  try {\n    await buildFacts()\n  } catch (error) {\n    return refusal('facts', error)\n  }",
    replace: "  announce('разбор')\n  try {\n    await buildFacts()\n  } catch (error) {\n    return { ok: true }\n  }",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "stale-never-shown",
    claim: "показать прежние числа прежним видом после отказа",
    mustRedden: "отказ со щелью: и текст, и изменённый вид чисел",
    file: "app/refresh-panel.tsx",
    find: "const stale = outcome.ok === false && outcome.stale",
    replace: "const stale = false",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "facts-refusal-text-generic",
    claim: "убрать текст щели у отказа разбора",
    mustRedden: "отказ разбора после удачных загрузок называет щель",
    alsoRedden: [
      { name: "текст отказа несёт причину, а не только шаг", why: "обезличенный текст отказа не несёт причину и в этой проверке" },
    ],
    file: "lib/metrics/refresh.ts",
    find: "     : `источники перечитаны, но разбор не удался: ${reason}. Числа ниже — от прежнего ` +\n          'удачного разбора и устарели.'",
    replace: "     : 'разбор не удался.'",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "step-not-named",
    claim: "убрать называние шага у отказа загрузки",
    mustRedden: "отказ загрузки Таблицы называет свой шаг, щели не объявляет и до разбора не доходит",
    alsoRedden: [
      { name: "отказ загрузки папки называет свой шаг и объявляет щель", why: "общая функция refusal() называет шаг для всех трёх шагов разом" },
      { name: "отказ разбора после удачных загрузок называет щель", why: "то же" },
      { name: "серверное действие кнопки за работу стучится только в Google", why: "то же: настоящий отказ загрузки Таблицы идёт через это же поле шага" },
    ],
    file: "lib/metrics/refresh.ts",
    find: "    step: STEP_LABEL[step],",
    replace: "    step: undefined as unknown as (typeof STEP_LABEL)[StepName],",
    tests: "все",
  },
  {
    id: "ads-refusal-wrong-step",
    claim: "назвать чужой шаг в отказе загрузки папки",
    mustRedden: "отказ загрузки папки называет свой шаг и объявляет щель",
    file: "lib/metrics/refresh.ts",
    find: "  announce('папка')\n  try {\n    await ingestAds()\n  } catch (error) {\n    return refusal('ingest:ads', error)\n  }",
    replace: "  announce('папка')\n  try {\n    await ingestAds()\n  } catch (error) {\n    return refusal('ingest:sheets', error)\n  }",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "ads-refusal-no-stale",
    claim: "снять щель у отказа загрузки папки",
    mustRedden: "отказ загрузки папки называет свой шаг и объявляет щель",
    file: "lib/metrics/refresh.ts",
    find: "  'ingest:ads': true,",
    replace: "  'ingest:ads': false,",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "real-call-missing-silent",
    claim: "завести запись команды без боевого вызова",
    mustRedden: "запись команды без боевого вызова — отказ, называющий имя",
    file: "lib/commands.ts",
    find: "    if (real === undefined) {\n      throw new Error(`у команды «${command.name}» нет боевого вызова в REAL_CALLS`)\n    }",
    replace: "",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "button-not-on-screen",
    claim: "не подключить кнопку к экрану",
    mustRedden: "экран содержит кнопку и оборачивает ею отчёт",
    file: "app/page.tsx",
    find: "  return (\n    <>\n      <LogoutButton />\n      {/*\n        Пометка холодного открытия — задача 5 куска S8. Человек, открывший страницу заново,\n        прежде видел устаревшие числа без всякого предупреждения: пометка приходила только от\n        неудачного нажатия кнопки, то есть только тому, кто нажимал. Это разные механизмы, и\n        оба нужны.\n      */}\n      {report.устарели === true && (\n        <p role=\"status\">\n          Числа отстали от источников: сырьё менялось после последнего разбора. Нажмите\n          «Обновить данные».\n        </p>\n      )}\n      <RefreshPanel>\n        <Dashboard report={report} />\n      </RefreshPanel>\n    </>\n  )",
    replace: "  return (\n    <>\n      <LogoutButton />\n      {report.устарели === true && (\n        <p role=\"status\">\n          Числа отстали от источников: сырьё менялось после последнего разбора. Нажмите\n          «Обновить данные».\n        </p>\n      )}\n      <Dashboard report={report} />\n    </>\n  )",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "button-bypasses-list",
    claim: "дать кнопке собственный путь к загрузке мимо списка команд",
    mustRedden: "кнопка зовёт только работы из списка команд, и все три",
    alsoRedden: [
      { name: "серверное действие кнопки за работу стучится только в Google", why: "обход списка на шаге Таблицы меняет и настоящий боевой прогон кнопки: шаг папки идёт в сеть вместо шага Таблицы" },
    ],
    file: "lib/metrics/refresh.ts",
    find: "const ingestSheets = deps.ingestSheets ?? stepFromCommands(commands, 'ingest:sheets')",
    replace: "const ingestSheets = deps.ingestSheets ?? (async () => {})",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "missing-step-silent",
    claim: "убрать отказ на шаге, которого нет в списке команд",
    mustRedden: "шага, которого нет в списке команд, кнопка не выдумывает",
    file: "lib/metrics/refresh.ts",
    find: "  const command = commands.find((entry) => entry.name === name)\n  if (command === undefined) {\n    throw new Error(`команды ${name} нет в списке — обход списка невозможен по построению`)\n  }\n  return command.real",
    replace: "  const command = commands.find((entry) => entry.name === name)\n  if (command === undefined) {\n    return async () => {}\n  }\n  return command.real",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "action-extra-fetch",
    claim: "дать серверному действию кнопки стук наружу мимо Google",
    mustRedden: "серверное действие кнопки за работу стучится только в Google",
    file: "app/refresh-action.ts",
    find: "export async function refreshAction(): Promise<RefreshOutcome> {\n  if ((await проверитьДоступ()) === 'отказать') redirect('/login')\n\n  try {\n    return await refreshEverything()\n  } finally {\n    revalidateAfterAttempt()\n  }\n}",
    replace: "export async function refreshAction(): Promise<RefreshOutcome> {\n  if ((await проверитьДоступ()) === 'отказать') redirect('/login')\n\n  try {\n    void fetch('http://наружу.invalid/не-google').catch(() => {})\n    return await refreshEverything()\n  } finally {\n    revalidateAfterAttempt()\n  }\n}",
    tests: "__tests__/metrics/refresh.test.tsx",
  },
  {
    id: "facts-extra-world",
    claim: "объявить шагу кнопки внешний мир сверх Google",
    mustRedden: "шаги кнопки не объявляют себе внешних миров сверх Google",
    alsoRedden: [
      { name: "обязательства команды 'facts' 'за работу не стучится наружу ни разу'", why: "тот же список outsideWorld команды facts сверяется и в обязательствах" },
    ],
    file: "lib/commands.ts",
    find: "    name: 'facts',\n    script: 'scripts/build-facts.ts',\n    refusal: 'разбор отменён',\n    outsideWorld: [],",
    replace: "    name: 'facts',\n    script: 'scripts/build-facts.ts',\n    refusal: 'разбор отменён',\n    outsideWorld: ['не-google'],",
    tests: "все",
  },
  {
    id: "sheets-extra-world",
    claim: "объявить пути кнопки внешний мир, до которого она не ходит",
    mustRedden: "шаги кнопки не объявляют себе внешних миров сверх Google",
    alsoRedden: [
      { name: "обязательства команды 'ingest:sheets' 'за работу не стучится наружу ни разу'", why: "тот же список outsideWorld команды ingest:sheets сверяется и в обязательствах" },
    ],
    file: "lib/commands.ts",
    find: "    name: 'ingest:sheets',\n    script: 'scripts/ingest-sheets.ts',\n    refusal: 'загрузка отменена',\n    outsideWorld: ['google'],",
    replace: "    name: 'ingest:sheets',\n    script: 'scripts/ingest-sheets.ts',\n    refusal: 'загрузка отменена',\n    outsideWorld: ['google', 'лишний-мир'],",
    tests: "все",
  },
  {
    id: "metrics-announce-after-work",
    claim: "называть цель после работы",
    mustRedden: "обязательства команды 'metrics' 'цель названа до первой работы'",
    alsoRedden: [
      { name: "цель названа до первого запроса", why: "withFactSnapshot называет цель для обеих проверок одним и тем же кодом" },
    ],
    file: "lib/metrics/report.ts",
    find: "  const target = resolveIngestTarget()\n  announce(target.label)",
    replace: "  const target = resolveIngestTarget()",
    andThen: { find: "    await guarded.query('begin isolation level repeatable read read only')", replace: "    await guarded.query('begin isolation level repeatable read read only')\n    announce(target.label)" },
    tests: "все",
  },
  {
    id: "metrics-network",
    claim: "позвать сеть из команды метрик",
    mustRedden: "обязательства команды 'metrics' 'за работу не стучится наружу ни разу'",
    file: "lib/metrics/report.ts",
    find: "  const target = resolveIngestTarget()\n  announce(target.label)",
    replace: "  void fetch('http://наружу.invalid/').catch(() => {})\n  const target = resolveIngestTarget()\n  announce(target.label)",
    tests: "__tests__/commands/obligations.test.ts",
  },
  {
    id: "metrics-bypass-registry",
    claim: "завести команду метрик в обход списка обязательств",
    mustRedden: "список команд каждый сценарий либо команда, либо назван не командой с причиной",
    alsoRedden: [
      { name: "список команд ни одна команда package.json не заводит сценарий в обход списка", why: "оба обхода списка команд обнаруживаются одним и тем же удалением записи metrics" },
    ],
    file: "lib/commands.ts",
    find: "  {\n    name: 'metrics',\n    script: 'scripts/print-metrics.ts',\n    refusal: 'команда метрик отменена',\n    // Слой метрик читает снимок фактов и никуда больше не ходит — ни в Google, ни в\n    // какую другую сеть.\n    outsideWorld: [],\n    run: (probes) =>\n      monthlyReport(undefined, { announce: probes.announce, connect: probes.connect }),\n  },",
    replace: "",
    tests: "__tests__/commands/obligations.test.ts",
  },
  {
    id: "default-month-any",
    claim: "взять месяц по умолчанию не последним с заказами",
    mustRedden: "месяц по умолчанию — последний, за который есть заказы",
    file: "lib/metrics/report.ts",
    find: "const resolvedMonth = month ?? months.find((m) => m.hasOrders)?.month ?? null",
    replace: "const resolvedMonth = month ?? months[0]?.month ?? null",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "months-include-empty",
    claim: "показать месяц, за который данных нет",
    mustRedden: "месяц по умолчанию — последний, за который есть заказы",
    alsoRedden: [
      { name: "пустой слой фактов не роняет отчёт", why: "выдуманный месяц попадает в список даже при пустом слое фактов" },
    ],
    file: "lib/metrics/sql.ts",
    find: "select am.month as month,\n       exists(select 1 from orders_months om where om.month = am.month) as has_orders\n  from all_months am\n order by am.month desc",
    replace: "select am.month as month,\n       exists(select 1 from orders_months om where om.month = am.month) as has_orders\n  from all_months am\n union all\n select '2099-01', false\n order by month desc",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "items-sort-by-sku",
    claim: "отсортировать таблицу товаров не по выручке",
    mustRedden: "товары отсортированы по чистой выручке убыванием, штуки — за вычетом возвращённых",
    file: "lib/metrics/sql.ts",
    find: " order by sum(net) desc",
    replace: " order by sku",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "items-units-no-refund",
    claim: "считать в таблице товаров штуки без вычета возвратов",
    mustRedden: "товары отсортированы по чистой выручке убыванием, штуки — за вычетом возвращённых",
    alsoRedden: [
      { name: "штуки товара не бывают отрицательными на экране", why: "та же колонка units таблицы товаров используется в обеих проверках" },
    ],
    file: "lib/metrics/sql.ts",
    find: "sum(greatest(units - refund_units, 0))::text as units,",
    replace: "sum(units)::text as units,",
    tests: "__tests__/metrics/report.test.ts",
  },
  {
    id: "month-param-ignored",
    claim: "не передавать месяц из адреса дальше отчёта",
    mustRedden: "месяц из адреса определяет, что видно на экране, а не месяц по умолчанию",
    alsoRedden: [
      { name: "кривой месяц в адресе показывает наш текст, а не падает", why: "оборванный довод месяца до `monthlyReport()` значит, что кривой ввод из адреса вообще не доходит до её проверки формы — отказа не будет, будет молча месяц по умолчанию" },
    ],
    file: "app/page.tsx",
    find: "report = await monthlyReport(monthParam)",
    replace: "report = await monthlyReport()",
    tests: "__tests__/metrics/screen-month.test.tsx",
  },
  {
    id: "nav-links-drop-month",
    claim: "увести ссылки переключателя месяца на / вместо своего месяца",
    mustRedden: "ссылки переключателя месяца ведут на /?m=<месяц>, а не на /",
    file: "app/page.tsx",
    find: "href={`/?m=${m.month}`}",
    replace: "href=\"/\"",
    tests: "__tests__/metrics/screen-month.test.tsx",
  },
  {
    id: "bad-month-crashes-page",
    claim: "убрать перехват отказа кривого месяца на экране",
    mustRedden: "кривой месяц в адресе показывает наш текст, а не падает",
    file: "app/page.tsx",
    find: "  let report: MonthReport\n  try {\n    report = await monthlyReport(monthParam)\n  } catch (error) {\n    // S8: различаем по **самому отказу**, а не по вводу. Отказ отчёта теперь называет свой вид\n    // сам (`ОтказОтчёта`), и оба вида показываются человеку страницей: кривой месяц он\n    // поправит в адресе, а «данные не читаются» ему не починить — но он обязан знать, что\n    // числа не показаны нарочно, а не потерялись.\n    //\n    // Текст отказа «данные не читаются» составлен нами и адреса базы не содержит по\n    // построению: подлинная причина остаётся в `cause`, то есть в журнале, а не на экране.\n    const вид = видОтказа(error)\n    if (вид !== null) {\n      // «Данные не читаются» показывается **нашим** постоянным текстом: сообщение отказа несёт\n      // подлинную причину вместе с адресом базы, и на экран оно не идёт вовсе. Кривой месяц —\n      // наоборот: его текст составлен нами и говорит человеку, что поправить в адресе.\n      const текст =\n        вид === 'данные не читаются' ? ТЕКСТ_ДАННЫЕ_НЕ_ЧИТАЮТСЯ : (error as Error).message\n      return (\n        <main>\n          <h1>Nordic Pet — прибыль</h1>\n          <p role=\"alert\">{текст}</p>\n          <LogoutButton />\n        </main>\n      )\n    }\n\n    // Наследство S6: принятая проверка того куска подставляет вместо отчёта **обычную**\n    // ошибку с текстом про форму месяца и ждёт, что страница её покажет. Ветка оставлена\n    // ради неё и только ради неё; настоящий отчёт сюда не попадает — он называет свой вид.\n    // Убрать её значит покрасить принятую проверку прошлого куска, а это находка к владельцу,\n    // а не мелочь по дороге: названа в теле pull request.\n    if (monthParam !== undefined && !ФОРМА_МЕСЯЦА.test(monthParam)) {\n      return (\n        <main>\n          <h1>Nordic Pet — прибыль</h1>\n          <p role=\"alert\">{(error as Error).message}</p>\n        </main>\n      )\n    }\n\n    throw error\n  }",
    replace: "  const report = await monthlyReport(monthParam)",
    tests: "__tests__/metrics/screen-month.test.tsx",
  },
  {
    id: "no-revalidate-after-refresh",
    claim: "не обновлять экран после нажатия кнопки",
    mustRedden: "удачный исход: экран ревалидируется",
    alsoRedden: [
      { name: "отказной исход: экран тоже ревалидируется — числа устарели, но не остаются прежними на вид", why: "тот же убранный вызов сторожит и отказный путь" },
      { name: "ошибка устройства (не операционный отказ): ревалидация всё равно доходит", why: "тот же убранный вызов сторожит и путь с брошенной ошибкой устройства" },
    ],
    file: "app/refresh-action.ts",
    find: "export async function refreshAction(): Promise<RefreshOutcome> {\n  if ((await проверитьДоступ()) === 'отказать') redirect('/login')\n\n  try {\n    return await refreshEverything()\n  } finally {\n    revalidateAfterAttempt()\n  }\n}",
    replace: "export async function refreshAction(): Promise<RefreshOutcome> {\n  if ((await проверитьДоступ()) === 'отказать') redirect('/login')\n\n  return refreshEverything()\n}",
    tests: "__tests__/metrics/refresh-action.test.ts",
  },
]
